// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\auth\registration_repository.go
//
// Generated by this command:
//
//	mockgen -typed -source .\internal\auth\registration_repository.go -destination .\internal\auth\mocks\registration_repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	auth "github.com/thoriqr/stash-it-backend/internal/auth"
	authdb "github.com/thoriqr/stash-it-backend/internal/auth/generated"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationRepository is a mock of RegistrationRepository interface.
type MockRegistrationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationRepositoryMockRecorder
	isgomock struct{}
}

// MockRegistrationRepositoryMockRecorder is the mock recorder for MockRegistrationRepository.
type MockRegistrationRepositoryMockRecorder struct {
	mock *MockRegistrationRepository
}

// NewMockRegistrationRepository creates a new mock instance.
func NewMockRegistrationRepository(ctrl *gomock.Controller) *MockRegistrationRepository {
	mock := &MockRegistrationRepository{ctrl: ctrl}
	mock.recorder = &MockRegistrationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationRepository) EXPECT() *MockRegistrationRepositoryMockRecorder {
	return m.recorder
}

// CompleteVerification mocks base method.
func (m *MockRegistrationRepository) CompleteVerification(ctx context.Context, params auth.CompleteVerificationParams) (authdb.RegistrationContinuation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteVerification", ctx, params)
	ret0, _ := ret[0].(authdb.RegistrationContinuation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteVerification indicates an expected call of CompleteVerification.
func (mr *MockRegistrationRepositoryMockRecorder) CompleteVerification(ctx, params any) *MockRegistrationRepositoryCompleteVerificationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteVerification", reflect.TypeOf((*MockRegistrationRepository)(nil).CompleteVerification), ctx, params)
	return &MockRegistrationRepositoryCompleteVerificationCall{Call: call}
}

// MockRegistrationRepositoryCompleteVerificationCall wrap *gomock.Call
type MockRegistrationRepositoryCompleteVerificationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationRepositoryCompleteVerificationCall) Return(arg0 authdb.RegistrationContinuation, arg1 error) *MockRegistrationRepositoryCompleteVerificationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationRepositoryCompleteVerificationCall) Do(f func(context.Context, auth.CompleteVerificationParams) (authdb.RegistrationContinuation, error)) *MockRegistrationRepositoryCompleteVerificationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationRepositoryCompleteVerificationCall) DoAndReturn(f func(context.Context, auth.CompleteVerificationParams) (authdb.RegistrationContinuation, error)) *MockRegistrationRepositoryCompleteVerificationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateManualRegistration mocks base method.
func (m *MockRegistrationRepository) CreateManualRegistration(ctx context.Context, params auth.CreateManualRegistrationParams) (authdb.VerificationRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManualRegistration", ctx, params)
	ret0, _ := ret[0].(authdb.VerificationRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateManualRegistration indicates an expected call of CreateManualRegistration.
func (mr *MockRegistrationRepositoryMockRecorder) CreateManualRegistration(ctx, params any) *MockRegistrationRepositoryCreateManualRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManualRegistration", reflect.TypeOf((*MockRegistrationRepository)(nil).CreateManualRegistration), ctx, params)
	return &MockRegistrationRepositoryCreateManualRegistrationCall{Call: call}
}

// MockRegistrationRepositoryCreateManualRegistrationCall wrap *gomock.Call
type MockRegistrationRepositoryCreateManualRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationRepositoryCreateManualRegistrationCall) Return(arg0 authdb.VerificationRequest, arg1 error) *MockRegistrationRepositoryCreateManualRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationRepositoryCreateManualRegistrationCall) Do(f func(context.Context, auth.CreateManualRegistrationParams) (authdb.VerificationRequest, error)) *MockRegistrationRepositoryCreateManualRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationRepositoryCreateManualRegistrationCall) DoAndReturn(f func(context.Context, auth.CreateManualRegistrationParams) (authdb.VerificationRequest, error)) *MockRegistrationRepositoryCreateManualRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FinalizeManualRegistration mocks base method.
func (m *MockRegistrationRepository) FinalizeManualRegistration(ctx context.Context, params auth.FinalizeManualRegistrationParams) (authdb.CreateUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeManualRegistration", ctx, params)
	ret0, _ := ret[0].(authdb.CreateUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeManualRegistration indicates an expected call of FinalizeManualRegistration.
func (mr *MockRegistrationRepositoryMockRecorder) FinalizeManualRegistration(ctx, params any) *MockRegistrationRepositoryFinalizeManualRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeManualRegistration", reflect.TypeOf((*MockRegistrationRepository)(nil).FinalizeManualRegistration), ctx, params)
	return &MockRegistrationRepositoryFinalizeManualRegistrationCall{Call: call}
}

// MockRegistrationRepositoryFinalizeManualRegistrationCall wrap *gomock.Call
type MockRegistrationRepositoryFinalizeManualRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationRepositoryFinalizeManualRegistrationCall) Return(arg0 authdb.CreateUserRow, arg1 error) *MockRegistrationRepositoryFinalizeManualRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationRepositoryFinalizeManualRegistrationCall) Do(f func(context.Context, auth.FinalizeManualRegistrationParams) (authdb.CreateUserRow, error)) *MockRegistrationRepositoryFinalizeManualRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationRepositoryFinalizeManualRegistrationCall) DoAndReturn(f func(context.Context, auth.FinalizeManualRegistrationParams) (authdb.CreateUserRow, error)) *MockRegistrationRepositoryFinalizeManualRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetActiveVerificationCode mocks base method.
func (m *MockRegistrationRepository) GetActiveVerificationCode(ctx context.Context, verificationRequestID uuid.UUID, maxAttempts int32) (authdb.VerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveVerificationCode", ctx, verificationRequestID, maxAttempts)
	ret0, _ := ret[0].(authdb.VerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveVerificationCode indicates an expected call of GetActiveVerificationCode.
func (mr *MockRegistrationRepositoryMockRecorder) GetActiveVerificationCode(ctx, verificationRequestID, maxAttempts any) *MockRegistrationRepositoryGetActiveVerificationCodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveVerificationCode", reflect.TypeOf((*MockRegistrationRepository)(nil).GetActiveVerificationCode), ctx, verificationRequestID, maxAttempts)
	return &MockRegistrationRepositoryGetActiveVerificationCodeCall{Call: call}
}

// MockRegistrationRepositoryGetActiveVerificationCodeCall wrap *gomock.Call
type MockRegistrationRepositoryGetActiveVerificationCodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationRepositoryGetActiveVerificationCodeCall) Return(arg0 authdb.VerificationCode, arg1 error) *MockRegistrationRepositoryGetActiveVerificationCodeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationRepositoryGetActiveVerificationCodeCall) Do(f func(context.Context, uuid.UUID, int32) (authdb.VerificationCode, error)) *MockRegistrationRepositoryGetActiveVerificationCodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationRepositoryGetActiveVerificationCodeCall) DoAndReturn(f func(context.Context, uuid.UUID, int32) (authdb.VerificationCode, error)) *MockRegistrationRepositoryGetActiveVerificationCodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPendingRegistrationByEmail mocks base method.
func (m *MockRegistrationRepository) GetPendingRegistrationByEmail(ctx context.Context, email string) (authdb.GetPendingRegistrationByEmailRow, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingRegistrationByEmail", ctx, email)
	ret0, _ := ret[0].(authdb.GetPendingRegistrationByEmailRow)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPendingRegistrationByEmail indicates an expected call of GetPendingRegistrationByEmail.
func (mr *MockRegistrationRepositoryMockRecorder) GetPendingRegistrationByEmail(ctx, email any) *MockRegistrationRepositoryGetPendingRegistrationByEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingRegistrationByEmail", reflect.TypeOf((*MockRegistrationRepository)(nil).GetPendingRegistrationByEmail), ctx, email)
	return &MockRegistrationRepositoryGetPendingRegistrationByEmailCall{Call: call}
}

// MockRegistrationRepositoryGetPendingRegistrationByEmailCall wrap *gomock.Call
type MockRegistrationRepositoryGetPendingRegistrationByEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationRepositoryGetPendingRegistrationByEmailCall) Return(arg0 authdb.GetPendingRegistrationByEmailRow, arg1 bool, arg2 error) *MockRegistrationRepositoryGetPendingRegistrationByEmailCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationRepositoryGetPendingRegistrationByEmailCall) Do(f func(context.Context, string) (authdb.GetPendingRegistrationByEmailRow, bool, error)) *MockRegistrationRepositoryGetPendingRegistrationByEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationRepositoryGetPendingRegistrationByEmailCall) DoAndReturn(f func(context.Context, string) (authdb.GetPendingRegistrationByEmailRow, bool, error)) *MockRegistrationRepositoryGetPendingRegistrationByEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRegistrationContinuation mocks base method.
func (m *MockRegistrationRepository) GetRegistrationContinuation(ctx context.Context, tokenHash string) (authdb.GetRegistrationContinuationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationContinuation", ctx, tokenHash)
	ret0, _ := ret[0].(authdb.GetRegistrationContinuationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationContinuation indicates an expected call of GetRegistrationContinuation.
func (mr *MockRegistrationRepositoryMockRecorder) GetRegistrationContinuation(ctx, tokenHash any) *MockRegistrationRepositoryGetRegistrationContinuationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationContinuation", reflect.TypeOf((*MockRegistrationRepository)(nil).GetRegistrationContinuation), ctx, tokenHash)
	return &MockRegistrationRepositoryGetRegistrationContinuationCall{Call: call}
}

// MockRegistrationRepositoryGetRegistrationContinuationCall wrap *gomock.Call
type MockRegistrationRepositoryGetRegistrationContinuationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationRepositoryGetRegistrationContinuationCall) Return(arg0 authdb.GetRegistrationContinuationRow, arg1 error) *MockRegistrationRepositoryGetRegistrationContinuationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationRepositoryGetRegistrationContinuationCall) Do(f func(context.Context, string) (authdb.GetRegistrationContinuationRow, error)) *MockRegistrationRepositoryGetRegistrationContinuationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationRepositoryGetRegistrationContinuationCall) DoAndReturn(f func(context.Context, string) (authdb.GetRegistrationContinuationRow, error)) *MockRegistrationRepositoryGetRegistrationContinuationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetVerification mocks base method.
func (m *MockRegistrationRepository) GetVerification(ctx context.Context, id uuid.UUID) (authdb.GetVerificationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerification", ctx, id)
	ret0, _ := ret[0].(authdb.GetVerificationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerification indicates an expected call of GetVerification.
func (mr *MockRegistrationRepositoryMockRecorder) GetVerification(ctx, id any) *MockRegistrationRepositoryGetVerificationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerification", reflect.TypeOf((*MockRegistrationRepository)(nil).GetVerification), ctx, id)
	return &MockRegistrationRepositoryGetVerificationCall{Call: call}
}

// MockRegistrationRepositoryGetVerificationCall wrap *gomock.Call
type MockRegistrationRepositoryGetVerificationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationRepositoryGetVerificationCall) Return(arg0 authdb.GetVerificationRow, arg1 error) *MockRegistrationRepositoryGetVerificationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationRepositoryGetVerificationCall) Do(f func(context.Context, uuid.UUID) (authdb.GetVerificationRow, error)) *MockRegistrationRepositoryGetVerificationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationRepositoryGetVerificationCall) DoAndReturn(f func(context.Context, uuid.UUID) (authdb.GetVerificationRow, error)) *MockRegistrationRepositoryGetVerificationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncrementVerificationCodeAttempts mocks base method.
func (m *MockRegistrationRepository) IncrementVerificationCodeAttempts(ctx context.Context, id uuid.UUID, maxAttempts int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementVerificationCodeAttempts", ctx, id, maxAttempts)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementVerificationCodeAttempts indicates an expected call of IncrementVerificationCodeAttempts.
func (mr *MockRegistrationRepositoryMockRecorder) IncrementVerificationCodeAttempts(ctx, id, maxAttempts any) *MockRegistrationRepositoryIncrementVerificationCodeAttemptsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementVerificationCodeAttempts", reflect.TypeOf((*MockRegistrationRepository)(nil).IncrementVerificationCodeAttempts), ctx, id, maxAttempts)
	return &MockRegistrationRepositoryIncrementVerificationCodeAttemptsCall{Call: call}
}

// MockRegistrationRepositoryIncrementVerificationCodeAttemptsCall wrap *gomock.Call
type MockRegistrationRepositoryIncrementVerificationCodeAttemptsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationRepositoryIncrementVerificationCodeAttemptsCall) Return(arg0 int32, arg1 error) *MockRegistrationRepositoryIncrementVerificationCodeAttemptsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationRepositoryIncrementVerificationCodeAttemptsCall) Do(f func(context.Context, uuid.UUID, int32) (int32, error)) *MockRegistrationRepositoryIncrementVerificationCodeAttemptsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationRepositoryIncrementVerificationCodeAttemptsCall) DoAndReturn(f func(context.Context, uuid.UUID, int32) (int32, error)) *MockRegistrationRepositoryIncrementVerificationCodeAttemptsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResendVerification mocks base method.
func (m *MockRegistrationRepository) ResendVerification(ctx context.Context, params auth.ResendVerificationParams) (authdb.VerificationRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendVerification", ctx, params)
	ret0, _ := ret[0].(authdb.VerificationRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResendVerification indicates an expected call of ResendVerification.
func (mr *MockRegistrationRepositoryMockRecorder) ResendVerification(ctx, params any) *MockRegistrationRepositoryResendVerificationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendVerification", reflect.TypeOf((*MockRegistrationRepository)(nil).ResendVerification), ctx, params)
	return &MockRegistrationRepositoryResendVerificationCall{Call: call}
}

// MockRegistrationRepositoryResendVerificationCall wrap *gomock.Call
type MockRegistrationRepositoryResendVerificationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationRepositoryResendVerificationCall) Return(arg0 authdb.VerificationRequest, arg1 error) *MockRegistrationRepositoryResendVerificationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationRepositoryResendVerificationCall) Do(f func(context.Context, auth.ResendVerificationParams) (authdb.VerificationRequest, error)) *MockRegistrationRepositoryResendVerificationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationRepositoryResendVerificationCall) DoAndReturn(f func(context.Context, auth.ResendVerificationParams) (authdb.VerificationRequest, error)) *MockRegistrationRepositoryResendVerificationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
