// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\api\auth\session\repository.go
//
// Generated by this command:
//
//	mockgen -typed -source .\internal\api\auth\session\repository.go -destination .\internal\api\auth\session\mocks\repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	session "github.com/thoriqr/stash-it-backend/internal/api/auth/session"
	sessiondb "github.com/thoriqr/stash-it-backend/internal/api/auth/session/generated"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountSessions mocks base method.
func (m *MockRepository) CountSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSessions", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSessions indicates an expected call of CountSessions.
func (mr *MockRepositoryMockRecorder) CountSessions(ctx, userID any) *MockRepositoryCountSessionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSessions", reflect.TypeOf((*MockRepository)(nil).CountSessions), ctx, userID)
	return &MockRepositoryCountSessionsCall{Call: call}
}

// MockRepositoryCountSessionsCall wrap *gomock.Call
type MockRepositoryCountSessionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCountSessionsCall) Return(arg0 int64, arg1 error) *MockRepositoryCountSessionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCountSessionsCall) Do(f func(context.Context, uuid.UUID) (int64, error)) *MockRepositoryCountSessionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCountSessionsCall) DoAndReturn(f func(context.Context, uuid.UUID) (int64, error)) *MockRepositoryCountSessionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSession mocks base method.
func (m *MockRepository) CreateSession(ctx context.Context, params sessiondb.CreateSessionParams, refreshTokenHash string) (sessiondb.Session, sessiondb.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, params, refreshTokenHash)
	ret0, _ := ret[0].(sessiondb.Session)
	ret1, _ := ret[1].(sessiondb.RefreshToken)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockRepositoryMockRecorder) CreateSession(ctx, params, refreshTokenHash any) *MockRepositoryCreateSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockRepository)(nil).CreateSession), ctx, params, refreshTokenHash)
	return &MockRepositoryCreateSessionCall{Call: call}
}

// MockRepositoryCreateSessionCall wrap *gomock.Call
type MockRepositoryCreateSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateSessionCall) Return(arg0 sessiondb.Session, arg1 sessiondb.RefreshToken, arg2 error) *MockRepositoryCreateSessionCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateSessionCall) Do(f func(context.Context, sessiondb.CreateSessionParams, string) (sessiondb.Session, sessiondb.RefreshToken, error)) *MockRepositoryCreateSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateSessionCall) DoAndReturn(f func(context.Context, sessiondb.CreateSessionParams, string) (sessiondb.Session, sessiondb.RefreshToken, error)) *MockRepositoryCreateSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRefreshTokenWithSession mocks base method.
func (m *MockRepository) GetRefreshTokenWithSession(ctx context.Context, tokenHash string) (sessiondb.GetRefreshTokenWithSessionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenWithSession", ctx, tokenHash)
	ret0, _ := ret[0].(sessiondb.GetRefreshTokenWithSessionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenWithSession indicates an expected call of GetRefreshTokenWithSession.
func (mr *MockRepositoryMockRecorder) GetRefreshTokenWithSession(ctx, tokenHash any) *MockRepositoryGetRefreshTokenWithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenWithSession", reflect.TypeOf((*MockRepository)(nil).GetRefreshTokenWithSession), ctx, tokenHash)
	return &MockRepositoryGetRefreshTokenWithSessionCall{Call: call}
}

// MockRepositoryGetRefreshTokenWithSessionCall wrap *gomock.Call
type MockRepositoryGetRefreshTokenWithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetRefreshTokenWithSessionCall) Return(arg0 sessiondb.GetRefreshTokenWithSessionRow, arg1 error) *MockRepositoryGetRefreshTokenWithSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetRefreshTokenWithSessionCall) Do(f func(context.Context, string) (sessiondb.GetRefreshTokenWithSessionRow, error)) *MockRepositoryGetRefreshTokenWithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetRefreshTokenWithSessionCall) DoAndReturn(f func(context.Context, string) (sessiondb.GetRefreshTokenWithSessionRow, error)) *MockRepositoryGetRefreshTokenWithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSessions mocks base method.
func (m *MockRepository) ListSessions(ctx context.Context, userID uuid.UUID, offset, limit int32) ([]sessiondb.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx, userID, offset, limit)
	ret0, _ := ret[0].([]sessiondb.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockRepositoryMockRecorder) ListSessions(ctx, userID, offset, limit any) *MockRepositoryListSessionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockRepository)(nil).ListSessions), ctx, userID, offset, limit)
	return &MockRepositoryListSessionsCall{Call: call}
}

// MockRepositoryListSessionsCall wrap *gomock.Call
type MockRepositoryListSessionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListSessionsCall) Return(arg0 []sessiondb.Session, arg1 error) *MockRepositoryListSessionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListSessionsCall) Do(f func(context.Context, uuid.UUID, int32, int32) ([]sessiondb.Session, error)) *MockRepositoryListSessionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListSessionsCall) DoAndReturn(f func(context.Context, uuid.UUID, int32, int32) ([]sessiondb.Session, error)) *MockRepositoryListSessionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RefreshToken mocks base method.
func (m *MockRepository) RefreshToken(ctx context.Context, tokenHash, newRefreshTokenHash string, policy session.RefreshTokenPolicy) (sessiondb.GetRefreshTokenWithSessionForUpdateRow, sessiondb.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, tokenHash, newRefreshTokenHash, policy)
	ret0, _ := ret[0].(sessiondb.GetRefreshTokenWithSessionForUpdateRow)
	ret1, _ := ret[1].(sessiondb.RefreshToken)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockRepositoryMockRecorder) RefreshToken(ctx, tokenHash, newRefreshTokenHash, policy any) *MockRepositoryRefreshTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockRepository)(nil).RefreshToken), ctx, tokenHash, newRefreshTokenHash, policy)
	return &MockRepositoryRefreshTokenCall{Call: call}
}

// MockRepositoryRefreshTokenCall wrap *gomock.Call
type MockRepositoryRefreshTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryRefreshTokenCall) Return(arg0 sessiondb.GetRefreshTokenWithSessionForUpdateRow, arg1 sessiondb.RefreshToken, arg2 error) *MockRepositoryRefreshTokenCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryRefreshTokenCall) Do(f func(context.Context, string, string, session.RefreshTokenPolicy) (sessiondb.GetRefreshTokenWithSessionForUpdateRow, sessiondb.RefreshToken, error)) *MockRepositoryRefreshTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryRefreshTokenCall) DoAndReturn(f func(context.Context, string, string, session.RefreshTokenPolicy) (sessiondb.GetRefreshTokenWithSessionForUpdateRow, sessiondb.RefreshToken, error)) *MockRepositoryRefreshTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeSession mocks base method.
func (m *MockRepository) RevokeSession(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockRepositoryMockRecorder) RevokeSession(ctx, sessionID any) *MockRepositoryRevokeSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockRepository)(nil).RevokeSession), ctx, sessionID)
	return &MockRepositoryRevokeSessionCall{Call: call}
}

// MockRepositoryRevokeSessionCall wrap *gomock.Call
type MockRepositoryRevokeSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryRevokeSessionCall) Return(arg0 error) *MockRepositoryRevokeSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryRevokeSessionCall) Do(f func(context.Context, uuid.UUID) error) *MockRepositoryRevokeSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryRevokeSessionCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockRepositoryRevokeSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeSessionForUser mocks base method.
func (m *MockRepository) RevokeSessionForUser(ctx context.Context, sessionID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionForUser", ctx, sessionID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionForUser indicates an expected call of RevokeSessionForUser.
func (mr *MockRepositoryMockRecorder) RevokeSessionForUser(ctx, sessionID, userID any) *MockRepositoryRevokeSessionForUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionForUser", reflect.TypeOf((*MockRepository)(nil).RevokeSessionForUser), ctx, sessionID, userID)
	return &MockRepositoryRevokeSessionForUserCall{Call: call}
}

// MockRepositoryRevokeSessionForUserCall wrap *gomock.Call
type MockRepositoryRevokeSessionForUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryRevokeSessionForUserCall) Return(arg0 error) *MockRepositoryRevokeSessionForUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryRevokeSessionForUserCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockRepositoryRevokeSessionForUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryRevokeSessionForUserCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockRepositoryRevokeSessionForUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
