// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\api\auth\session\service.go
//
// Generated by this command:
//
//	mockgen -typed -source .\internal\api\auth\session\service.go -destination .\internal\api\auth\session\mocks\service.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	session "github.com/thoriqr/stash-it-backend/internal/api/auth/session"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionCreator is a mock of SessionCreator interface.
type MockSessionCreator struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCreatorMockRecorder
	isgomock struct{}
}

// MockSessionCreatorMockRecorder is the mock recorder for MockSessionCreator.
type MockSessionCreatorMockRecorder struct {
	mock *MockSessionCreator
}

// NewMockSessionCreator creates a new mock instance.
func NewMockSessionCreator(ctrl *gomock.Controller) *MockSessionCreator {
	mock := &MockSessionCreator{ctrl: ctrl}
	mock.recorder = &MockSessionCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCreator) EXPECT() *MockSessionCreatorMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionCreator) CreateSession(ctx context.Context, userID uuid.UUID, metadata session.SessionMetadata) (session.CreateSessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, userID, metadata)
	ret0, _ := ret[0].(session.CreateSessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionCreatorMockRecorder) CreateSession(ctx, userID, metadata any) *MockSessionCreatorCreateSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionCreator)(nil).CreateSession), ctx, userID, metadata)
	return &MockSessionCreatorCreateSessionCall{Call: call}
}

// MockSessionCreatorCreateSessionCall wrap *gomock.Call
type MockSessionCreatorCreateSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionCreatorCreateSessionCall) Return(arg0 session.CreateSessionResult, arg1 error) *MockSessionCreatorCreateSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionCreatorCreateSessionCall) Do(f func(context.Context, uuid.UUID, session.SessionMetadata) (session.CreateSessionResult, error)) *MockSessionCreatorCreateSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionCreatorCreateSessionCall) DoAndReturn(f func(context.Context, uuid.UUID, session.SessionMetadata) (session.CreateSessionResult, error)) *MockSessionCreatorCreateSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// ListSessions mocks base method.
func (m *MockSessionService) ListSessions(ctx context.Context, userID uuid.UUID, page, limit int) (session.ListSessionsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx, userID, page, limit)
	ret0, _ := ret[0].(session.ListSessionsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockSessionServiceMockRecorder) ListSessions(ctx, userID, page, limit any) *MockSessionServiceListSessionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockSessionService)(nil).ListSessions), ctx, userID, page, limit)
	return &MockSessionServiceListSessionsCall{Call: call}
}

// MockSessionServiceListSessionsCall wrap *gomock.Call
type MockSessionServiceListSessionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionServiceListSessionsCall) Return(arg0 session.ListSessionsResult, arg1 error) *MockSessionServiceListSessionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionServiceListSessionsCall) Do(f func(context.Context, uuid.UUID, int, int) (session.ListSessionsResult, error)) *MockSessionServiceListSessionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionServiceListSessionsCall) DoAndReturn(f func(context.Context, uuid.UUID, int, int) (session.ListSessionsResult, error)) *MockSessionServiceListSessionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Logout mocks base method.
func (m *MockSessionService) Logout(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockSessionServiceMockRecorder) Logout(ctx, sessionID any) *MockSessionServiceLogoutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockSessionService)(nil).Logout), ctx, sessionID)
	return &MockSessionServiceLogoutCall{Call: call}
}

// MockSessionServiceLogoutCall wrap *gomock.Call
type MockSessionServiceLogoutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionServiceLogoutCall) Return(arg0 error) *MockSessionServiceLogoutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionServiceLogoutCall) Do(f func(context.Context, uuid.UUID) error) *MockSessionServiceLogoutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionServiceLogoutCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockSessionServiceLogoutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RefreshToken mocks base method.
func (m *MockSessionService) RefreshToken(ctx context.Context, refreshToken string) (session.RefreshTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(session.RefreshTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockSessionServiceMockRecorder) RefreshToken(ctx, refreshToken any) *MockSessionServiceRefreshTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockSessionService)(nil).RefreshToken), ctx, refreshToken)
	return &MockSessionServiceRefreshTokenCall{Call: call}
}

// MockSessionServiceRefreshTokenCall wrap *gomock.Call
type MockSessionServiceRefreshTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionServiceRefreshTokenCall) Return(arg0 session.RefreshTokenResult, arg1 error) *MockSessionServiceRefreshTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionServiceRefreshTokenCall) Do(f func(context.Context, string) (session.RefreshTokenResult, error)) *MockSessionServiceRefreshTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionServiceRefreshTokenCall) DoAndReturn(f func(context.Context, string) (session.RefreshTokenResult, error)) *MockSessionServiceRefreshTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeSessionForUser mocks base method.
func (m *MockSessionService) RevokeSessionForUser(ctx context.Context, userID, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionForUser", ctx, userID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionForUser indicates an expected call of RevokeSessionForUser.
func (mr *MockSessionServiceMockRecorder) RevokeSessionForUser(ctx, userID, sessionID any) *MockSessionServiceRevokeSessionForUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionForUser", reflect.TypeOf((*MockSessionService)(nil).RevokeSessionForUser), ctx, userID, sessionID)
	return &MockSessionServiceRevokeSessionForUserCall{Call: call}
}

// MockSessionServiceRevokeSessionForUserCall wrap *gomock.Call
type MockSessionServiceRevokeSessionForUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionServiceRevokeSessionForUserCall) Return(arg0 error) *MockSessionServiceRevokeSessionForUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionServiceRevokeSessionForUserCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockSessionServiceRevokeSessionForUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionServiceRevokeSessionForUserCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockSessionServiceRevokeSessionForUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
