// Code generated by MockGen. DO NOT EDIT.
// Source: internal\worker\enrichment\types.go
//
// Generated by this command:
//
//	mockgen -typed -source internal\worker\enrichment\types.go -destination internal\worker\enrichment\mocks\enricher.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	enrichment "github.com/thoriqr/stash-it-backend/internal/enrichment"
	gomock "go.uber.org/mock/gomock"
)

// MockSavedItemOrganizer is a mock of SavedItemOrganizer interface.
type MockSavedItemOrganizer struct {
	ctrl     *gomock.Controller
	recorder *MockSavedItemOrganizerMockRecorder
	isgomock struct{}
}

// MockSavedItemOrganizerMockRecorder is the mock recorder for MockSavedItemOrganizer.
type MockSavedItemOrganizerMockRecorder struct {
	mock *MockSavedItemOrganizer
}

// NewMockSavedItemOrganizer creates a new mock instance.
func NewMockSavedItemOrganizer(ctrl *gomock.Controller) *MockSavedItemOrganizer {
	mock := &MockSavedItemOrganizer{ctrl: ctrl}
	mock.recorder = &MockSavedItemOrganizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSavedItemOrganizer) EXPECT() *MockSavedItemOrganizerMockRecorder {
	return m.recorder
}

// EnqueueSavedItemOrganization mocks base method.
func (m *MockSavedItemOrganizer) EnqueueSavedItemOrganization(ctx context.Context, savedItemID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueSavedItemOrganization", ctx, savedItemID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueSavedItemOrganization indicates an expected call of EnqueueSavedItemOrganization.
func (mr *MockSavedItemOrganizerMockRecorder) EnqueueSavedItemOrganization(ctx, savedItemID, userID any) *MockSavedItemOrganizerEnqueueSavedItemOrganizationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueSavedItemOrganization", reflect.TypeOf((*MockSavedItemOrganizer)(nil).EnqueueSavedItemOrganization), ctx, savedItemID, userID)
	return &MockSavedItemOrganizerEnqueueSavedItemOrganizationCall{Call: call}
}

// MockSavedItemOrganizerEnqueueSavedItemOrganizationCall wrap *gomock.Call
type MockSavedItemOrganizerEnqueueSavedItemOrganizationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSavedItemOrganizerEnqueueSavedItemOrganizationCall) Return(arg0 error) *MockSavedItemOrganizerEnqueueSavedItemOrganizationCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSavedItemOrganizerEnqueueSavedItemOrganizationCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockSavedItemOrganizerEnqueueSavedItemOrganizationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSavedItemOrganizerEnqueueSavedItemOrganizationCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockSavedItemOrganizerEnqueueSavedItemOrganizationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMetadataEnricher is a mock of MetadataEnricher interface.
type MockMetadataEnricher struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataEnricherMockRecorder
	isgomock struct{}
}

// MockMetadataEnricherMockRecorder is the mock recorder for MockMetadataEnricher.
type MockMetadataEnricherMockRecorder struct {
	mock *MockMetadataEnricher
}

// NewMockMetadataEnricher creates a new mock instance.
func NewMockMetadataEnricher(ctrl *gomock.Controller) *MockMetadataEnricher {
	mock := &MockMetadataEnricher{ctrl: ctrl}
	mock.recorder = &MockMetadataEnricherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataEnricher) EXPECT() *MockMetadataEnricherMockRecorder {
	return m.recorder
}

// Enrich mocks base method.
func (m *MockMetadataEnricher) Enrich(ctx context.Context, rawURL string) (enrichment.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrich", ctx, rawURL)
	ret0, _ := ret[0].(enrichment.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enrich indicates an expected call of Enrich.
func (mr *MockMetadataEnricherMockRecorder) Enrich(ctx, rawURL any) *MockMetadataEnricherEnrichCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrich", reflect.TypeOf((*MockMetadataEnricher)(nil).Enrich), ctx, rawURL)
	return &MockMetadataEnricherEnrichCall{Call: call}
}

// MockMetadataEnricherEnrichCall wrap *gomock.Call
type MockMetadataEnricherEnrichCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetadataEnricherEnrichCall) Return(arg0 enrichment.Metadata, arg1 error) *MockMetadataEnricherEnrichCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetadataEnricherEnrichCall) Do(f func(context.Context, string) (enrichment.Metadata, error)) *MockMetadataEnricherEnrichCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetadataEnricherEnrichCall) DoAndReturn(f func(context.Context, string) (enrichment.Metadata, error)) *MockMetadataEnricherEnrichCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
