// Code generated by MockGen. DO NOT EDIT.
// Source: internal\worker\enrichment\repository.go
//
// Generated by this command:
//
//	mockgen -typed -source internal\worker\enrichment\repository.go -destination internal\worker\enrichment\mocks\repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	enrichment "github.com/thoriqr/stash-it-backend/internal/worker/enrichment"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CompleteSavedItemEnrichment mocks base method.
func (m *MockRepository) CompleteSavedItemEnrichment(ctx context.Context, params enrichment.CompleteSavedItemEnrichmentParams) (enrichment.CompletedSavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSavedItemEnrichment", ctx, params)
	ret0, _ := ret[0].(enrichment.CompletedSavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteSavedItemEnrichment indicates an expected call of CompleteSavedItemEnrichment.
func (mr *MockRepositoryMockRecorder) CompleteSavedItemEnrichment(ctx, params any) *MockRepositoryCompleteSavedItemEnrichmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSavedItemEnrichment", reflect.TypeOf((*MockRepository)(nil).CompleteSavedItemEnrichment), ctx, params)
	return &MockRepositoryCompleteSavedItemEnrichmentCall{Call: call}
}

// MockRepositoryCompleteSavedItemEnrichmentCall wrap *gomock.Call
type MockRepositoryCompleteSavedItemEnrichmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCompleteSavedItemEnrichmentCall) Return(arg0 enrichment.CompletedSavedItem, arg1 error) *MockRepositoryCompleteSavedItemEnrichmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCompleteSavedItemEnrichmentCall) Do(f func(context.Context, enrichment.CompleteSavedItemEnrichmentParams) (enrichment.CompletedSavedItem, error)) *MockRepositoryCompleteSavedItemEnrichmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCompleteSavedItemEnrichmentCall) DoAndReturn(f func(context.Context, enrichment.CompleteSavedItemEnrichmentParams) (enrichment.CompletedSavedItem, error)) *MockRepositoryCompleteSavedItemEnrichmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FailSavedItemEnrichment mocks base method.
func (m *MockRepository) FailSavedItemEnrichment(ctx context.Context, savedItemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailSavedItemEnrichment", ctx, savedItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailSavedItemEnrichment indicates an expected call of FailSavedItemEnrichment.
func (mr *MockRepositoryMockRecorder) FailSavedItemEnrichment(ctx, savedItemID any) *MockRepositoryFailSavedItemEnrichmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailSavedItemEnrichment", reflect.TypeOf((*MockRepository)(nil).FailSavedItemEnrichment), ctx, savedItemID)
	return &MockRepositoryFailSavedItemEnrichmentCall{Call: call}
}

// MockRepositoryFailSavedItemEnrichmentCall wrap *gomock.Call
type MockRepositoryFailSavedItemEnrichmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFailSavedItemEnrichmentCall) Return(arg0 error) *MockRepositoryFailSavedItemEnrichmentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFailSavedItemEnrichmentCall) Do(f func(context.Context, uuid.UUID) error) *MockRepositoryFailSavedItemEnrichmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFailSavedItemEnrichmentCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockRepositoryFailSavedItemEnrichmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSavedItemForBackgroundEnrichment mocks base method.
func (m *MockRepository) GetSavedItemForBackgroundEnrichment(ctx context.Context, savedItemID uuid.UUID) (enrichment.SavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavedItemForBackgroundEnrichment", ctx, savedItemID)
	ret0, _ := ret[0].(enrichment.SavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSavedItemForBackgroundEnrichment indicates an expected call of GetSavedItemForBackgroundEnrichment.
func (mr *MockRepositoryMockRecorder) GetSavedItemForBackgroundEnrichment(ctx, savedItemID any) *MockRepositoryGetSavedItemForBackgroundEnrichmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavedItemForBackgroundEnrichment", reflect.TypeOf((*MockRepository)(nil).GetSavedItemForBackgroundEnrichment), ctx, savedItemID)
	return &MockRepositoryGetSavedItemForBackgroundEnrichmentCall{Call: call}
}

// MockRepositoryGetSavedItemForBackgroundEnrichmentCall wrap *gomock.Call
type MockRepositoryGetSavedItemForBackgroundEnrichmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetSavedItemForBackgroundEnrichmentCall) Return(arg0 enrichment.SavedItem, arg1 error) *MockRepositoryGetSavedItemForBackgroundEnrichmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetSavedItemForBackgroundEnrichmentCall) Do(f func(context.Context, uuid.UUID) (enrichment.SavedItem, error)) *MockRepositoryGetSavedItemForBackgroundEnrichmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetSavedItemForBackgroundEnrichmentCall) DoAndReturn(f func(context.Context, uuid.UUID) (enrichment.SavedItem, error)) *MockRepositoryGetSavedItemForBackgroundEnrichmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
