// Code generated by MockGen. DO NOT EDIT.
// Source: internal\worker\enrichment\service.go
//
// Generated by this command:
//
//	mockgen -typed -source internal\worker\enrichment\service.go -destination internal\worker\enrichment\mocks\service.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// EnrichSavedItem mocks base method.
func (m *MockService) EnrichSavedItem(ctx context.Context, savedItemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnrichSavedItem", ctx, savedItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnrichSavedItem indicates an expected call of EnrichSavedItem.
func (mr *MockServiceMockRecorder) EnrichSavedItem(ctx, savedItemID any) *MockServiceEnrichSavedItemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrichSavedItem", reflect.TypeOf((*MockService)(nil).EnrichSavedItem), ctx, savedItemID)
	return &MockServiceEnrichSavedItemCall{Call: call}
}

// MockServiceEnrichSavedItemCall wrap *gomock.Call
type MockServiceEnrichSavedItemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceEnrichSavedItemCall) Return(arg0 error) *MockServiceEnrichSavedItemCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceEnrichSavedItemCall) Do(f func(context.Context, uuid.UUID) error) *MockServiceEnrichSavedItemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceEnrichSavedItemCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockServiceEnrichSavedItemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
