ALTER TABLE verification_requests
RENAME COLUMN resend_count TO pin_issued_count;

ALTER TABLE verification_requests
RENAME CONSTRAINT verification_requests_resend_count_check
TO verification_requests_pin_issued_count_check;