// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\api\auth\login\repository.go
//
// Generated by this command:
//
//	mockgen -typed -source .\internal\api\auth\login\repository.go -destination .\internal\api\auth\login\mocks\repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	logindb "github.com/thoriqr/stash-it-backend/internal/api/auth/login/generated"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetUserForLogin mocks base method.
func (m *MockRepository) GetUserForLogin(ctx context.Context, email string) (logindb.GetUserForLoginRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserForLogin", ctx, email)
	ret0, _ := ret[0].(logindb.GetUserForLoginRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserForLogin indicates an expected call of GetUserForLogin.
func (mr *MockRepositoryMockRecorder) GetUserForLogin(ctx, email any) *MockRepositoryGetUserForLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserForLogin", reflect.TypeOf((*MockRepository)(nil).GetUserForLogin), ctx, email)
	return &MockRepositoryGetUserForLoginCall{Call: call}
}

// MockRepositoryGetUserForLoginCall wrap *gomock.Call
type MockRepositoryGetUserForLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetUserForLoginCall) Return(arg0 logindb.GetUserForLoginRow, arg1 error) *MockRepositoryGetUserForLoginCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetUserForLoginCall) Do(f func(context.Context, string) (logindb.GetUserForLoginRow, error)) *MockRepositoryGetUserForLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetUserForLoginCall) DoAndReturn(f func(context.Context, string) (logindb.GetUserForLoginRow, error)) *MockRepositoryGetUserForLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
