// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\api\auth\login\service.go
//
// Generated by this command:
//
//	mockgen -typed -source .\internal\api\auth\login\service.go -destination .\internal\api\auth\login\mocks\service.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks
