// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/collection/repository.go
//
// Generated by this command:
//
//	mockgen -typed -source internal/api/collection/repository.go -destination internal/api/collection/mocks/repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	collection "github.com/thoriqr/stash-it-backend/internal/api/collection"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteCollection mocks base method.
func (m *MockRepository) DeleteCollection(ctx context.Context, params collection.DeleteCollectionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockRepositoryMockRecorder) DeleteCollection(ctx, params any) *MockRepositoryDeleteCollectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockRepository)(nil).DeleteCollection), ctx, params)
	return &MockRepositoryDeleteCollectionCall{Call: call}
}

// MockRepositoryDeleteCollectionCall wrap *gomock.Call
type MockRepositoryDeleteCollectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDeleteCollectionCall) Return(arg0 error) *MockRepositoryDeleteCollectionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDeleteCollectionCall) Do(f func(context.Context, collection.DeleteCollectionParams) error) *MockRepositoryDeleteCollectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDeleteCollectionCall) DoAndReturn(f func(context.Context, collection.DeleteCollectionParams) error) *MockRepositoryDeleteCollectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutSavedItemIntoUserCollection mocks base method.
func (m *MockRepository) PutSavedItemIntoUserCollection(ctx context.Context, params collection.PutSavedItemIntoUserCollectionParams) (collection.PutSavedItemIntoUserCollectionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutSavedItemIntoUserCollection", ctx, params)
	ret0, _ := ret[0].(collection.PutSavedItemIntoUserCollectionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutSavedItemIntoUserCollection indicates an expected call of PutSavedItemIntoUserCollection.
func (mr *MockRepositoryMockRecorder) PutSavedItemIntoUserCollection(ctx, params any) *MockRepositoryPutSavedItemIntoUserCollectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutSavedItemIntoUserCollection", reflect.TypeOf((*MockRepository)(nil).PutSavedItemIntoUserCollection), ctx, params)
	return &MockRepositoryPutSavedItemIntoUserCollectionCall{Call: call}
}

// MockRepositoryPutSavedItemIntoUserCollectionCall wrap *gomock.Call
type MockRepositoryPutSavedItemIntoUserCollectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryPutSavedItemIntoUserCollectionCall) Return(arg0 collection.PutSavedItemIntoUserCollectionResult, arg1 error) *MockRepositoryPutSavedItemIntoUserCollectionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryPutSavedItemIntoUserCollectionCall) Do(f func(context.Context, collection.PutSavedItemIntoUserCollectionParams) (collection.PutSavedItemIntoUserCollectionResult, error)) *MockRepositoryPutSavedItemIntoUserCollectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryPutSavedItemIntoUserCollectionCall) DoAndReturn(f func(context.Context, collection.PutSavedItemIntoUserCollectionParams) (collection.PutSavedItemIntoUserCollectionResult, error)) *MockRepositoryPutSavedItemIntoUserCollectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
