// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\api\auth\registration\repository.go
//
// Generated by this command:
//
//	mockgen -typed -source .\internal\api\auth\registration\repository.go -destination .\internal\api\auth\registration\mocks\repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	registration "github.com/thoriqr/stash-it-backend/internal/api/auth/registration"
	registrationdb "github.com/thoriqr/stash-it-backend/internal/api/auth/registration/generated"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CompleteVerification mocks base method.
func (m *MockRepository) CompleteVerification(ctx context.Context, params registration.CompleteVerificationParams) (registrationdb.RegistrationContinuation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteVerification", ctx, params)
	ret0, _ := ret[0].(registrationdb.RegistrationContinuation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteVerification indicates an expected call of CompleteVerification.
func (mr *MockRepositoryMockRecorder) CompleteVerification(ctx, params any) *MockRepositoryCompleteVerificationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteVerification", reflect.TypeOf((*MockRepository)(nil).CompleteVerification), ctx, params)
	return &MockRepositoryCompleteVerificationCall{Call: call}
}

// MockRepositoryCompleteVerificationCall wrap *gomock.Call
type MockRepositoryCompleteVerificationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCompleteVerificationCall) Return(arg0 registrationdb.RegistrationContinuation, arg1 error) *MockRepositoryCompleteVerificationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCompleteVerificationCall) Do(f func(context.Context, registration.CompleteVerificationParams) (registrationdb.RegistrationContinuation, error)) *MockRepositoryCompleteVerificationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCompleteVerificationCall) DoAndReturn(f func(context.Context, registration.CompleteVerificationParams) (registrationdb.RegistrationContinuation, error)) *MockRepositoryCompleteVerificationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateManualRegistration mocks base method.
func (m *MockRepository) CreateManualRegistration(ctx context.Context, params registration.CreateManualRegistrationParams) (registration.CreateManualRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManualRegistration", ctx, params)
	ret0, _ := ret[0].(registration.CreateManualRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateManualRegistration indicates an expected call of CreateManualRegistration.
func (mr *MockRepositoryMockRecorder) CreateManualRegistration(ctx, params any) *MockRepositoryCreateManualRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManualRegistration", reflect.TypeOf((*MockRepository)(nil).CreateManualRegistration), ctx, params)
	return &MockRepositoryCreateManualRegistrationCall{Call: call}
}

// MockRepositoryCreateManualRegistrationCall wrap *gomock.Call
type MockRepositoryCreateManualRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateManualRegistrationCall) Return(arg0 registration.CreateManualRegistrationResult, arg1 error) *MockRepositoryCreateManualRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateManualRegistrationCall) Do(f func(context.Context, registration.CreateManualRegistrationParams) (registration.CreateManualRegistrationResult, error)) *MockRepositoryCreateManualRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateManualRegistrationCall) DoAndReturn(f func(context.Context, registration.CreateManualRegistrationParams) (registration.CreateManualRegistrationResult, error)) *MockRepositoryCreateManualRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FinalizeManualRegistration mocks base method.
func (m *MockRepository) FinalizeManualRegistration(ctx context.Context, params registration.FinalizeManualRegistrationParams) (registrationdb.CreateUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeManualRegistration", ctx, params)
	ret0, _ := ret[0].(registrationdb.CreateUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeManualRegistration indicates an expected call of FinalizeManualRegistration.
func (mr *MockRepositoryMockRecorder) FinalizeManualRegistration(ctx, params any) *MockRepositoryFinalizeManualRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeManualRegistration", reflect.TypeOf((*MockRepository)(nil).FinalizeManualRegistration), ctx, params)
	return &MockRepositoryFinalizeManualRegistrationCall{Call: call}
}

// MockRepositoryFinalizeManualRegistrationCall wrap *gomock.Call
type MockRepositoryFinalizeManualRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFinalizeManualRegistrationCall) Return(arg0 registrationdb.CreateUserRow, arg1 error) *MockRepositoryFinalizeManualRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFinalizeManualRegistrationCall) Do(f func(context.Context, registration.FinalizeManualRegistrationParams) (registrationdb.CreateUserRow, error)) *MockRepositoryFinalizeManualRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFinalizeManualRegistrationCall) DoAndReturn(f func(context.Context, registration.FinalizeManualRegistrationParams) (registrationdb.CreateUserRow, error)) *MockRepositoryFinalizeManualRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetActiveVerificationCode mocks base method.
func (m *MockRepository) GetActiveVerificationCode(ctx context.Context, verificationRequestID uuid.UUID, maxAttempts int32) (registrationdb.VerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveVerificationCode", ctx, verificationRequestID, maxAttempts)
	ret0, _ := ret[0].(registrationdb.VerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveVerificationCode indicates an expected call of GetActiveVerificationCode.
func (mr *MockRepositoryMockRecorder) GetActiveVerificationCode(ctx, verificationRequestID, maxAttempts any) *MockRepositoryGetActiveVerificationCodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveVerificationCode", reflect.TypeOf((*MockRepository)(nil).GetActiveVerificationCode), ctx, verificationRequestID, maxAttempts)
	return &MockRepositoryGetActiveVerificationCodeCall{Call: call}
}

// MockRepositoryGetActiveVerificationCodeCall wrap *gomock.Call
type MockRepositoryGetActiveVerificationCodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetActiveVerificationCodeCall) Return(arg0 registrationdb.VerificationCode, arg1 error) *MockRepositoryGetActiveVerificationCodeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetActiveVerificationCodeCall) Do(f func(context.Context, uuid.UUID, int32) (registrationdb.VerificationCode, error)) *MockRepositoryGetActiveVerificationCodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetActiveVerificationCodeCall) DoAndReturn(f func(context.Context, uuid.UUID, int32) (registrationdb.VerificationCode, error)) *MockRepositoryGetActiveVerificationCodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCompletedRegistrationByEmail mocks base method.
func (m *MockRepository) GetCompletedRegistrationByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompletedRegistrationByEmail", ctx, email)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletedRegistrationByEmail indicates an expected call of GetCompletedRegistrationByEmail.
func (mr *MockRepositoryMockRecorder) GetCompletedRegistrationByEmail(ctx, email any) *MockRepositoryGetCompletedRegistrationByEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedRegistrationByEmail", reflect.TypeOf((*MockRepository)(nil).GetCompletedRegistrationByEmail), ctx, email)
	return &MockRepositoryGetCompletedRegistrationByEmailCall{Call: call}
}

// MockRepositoryGetCompletedRegistrationByEmailCall wrap *gomock.Call
type MockRepositoryGetCompletedRegistrationByEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetCompletedRegistrationByEmailCall) Return(arg0 uuid.UUID, arg1 error) *MockRepositoryGetCompletedRegistrationByEmailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetCompletedRegistrationByEmailCall) Do(f func(context.Context, string) (uuid.UUID, error)) *MockRepositoryGetCompletedRegistrationByEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetCompletedRegistrationByEmailCall) DoAndReturn(f func(context.Context, string) (uuid.UUID, error)) *MockRepositoryGetCompletedRegistrationByEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRegistrationContinuation mocks base method.
func (m *MockRepository) GetRegistrationContinuation(ctx context.Context, tokenHash string) (registrationdb.GetRegistrationContinuationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationContinuation", ctx, tokenHash)
	ret0, _ := ret[0].(registrationdb.GetRegistrationContinuationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationContinuation indicates an expected call of GetRegistrationContinuation.
func (mr *MockRepositoryMockRecorder) GetRegistrationContinuation(ctx, tokenHash any) *MockRepositoryGetRegistrationContinuationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationContinuation", reflect.TypeOf((*MockRepository)(nil).GetRegistrationContinuation), ctx, tokenHash)
	return &MockRepositoryGetRegistrationContinuationCall{Call: call}
}

// MockRepositoryGetRegistrationContinuationCall wrap *gomock.Call
type MockRepositoryGetRegistrationContinuationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetRegistrationContinuationCall) Return(arg0 registrationdb.GetRegistrationContinuationRow, arg1 error) *MockRepositoryGetRegistrationContinuationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetRegistrationContinuationCall) Do(f func(context.Context, string) (registrationdb.GetRegistrationContinuationRow, error)) *MockRepositoryGetRegistrationContinuationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetRegistrationContinuationCall) DoAndReturn(f func(context.Context, string) (registrationdb.GetRegistrationContinuationRow, error)) *MockRepositoryGetRegistrationContinuationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetVerification mocks base method.
func (m *MockRepository) GetVerification(ctx context.Context, id uuid.UUID) (registrationdb.GetVerificationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerification", ctx, id)
	ret0, _ := ret[0].(registrationdb.GetVerificationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerification indicates an expected call of GetVerification.
func (mr *MockRepositoryMockRecorder) GetVerification(ctx, id any) *MockRepositoryGetVerificationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerification", reflect.TypeOf((*MockRepository)(nil).GetVerification), ctx, id)
	return &MockRepositoryGetVerificationCall{Call: call}
}

// MockRepositoryGetVerificationCall wrap *gomock.Call
type MockRepositoryGetVerificationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetVerificationCall) Return(arg0 registrationdb.GetVerificationRow, arg1 error) *MockRepositoryGetVerificationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetVerificationCall) Do(f func(context.Context, uuid.UUID) (registrationdb.GetVerificationRow, error)) *MockRepositoryGetVerificationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetVerificationCall) DoAndReturn(f func(context.Context, uuid.UUID) (registrationdb.GetVerificationRow, error)) *MockRepositoryGetVerificationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncrementVerificationCodeAttempts mocks base method.
func (m *MockRepository) IncrementVerificationCodeAttempts(ctx context.Context, id uuid.UUID, maxAttempts int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementVerificationCodeAttempts", ctx, id, maxAttempts)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementVerificationCodeAttempts indicates an expected call of IncrementVerificationCodeAttempts.
func (mr *MockRepositoryMockRecorder) IncrementVerificationCodeAttempts(ctx, id, maxAttempts any) *MockRepositoryIncrementVerificationCodeAttemptsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementVerificationCodeAttempts", reflect.TypeOf((*MockRepository)(nil).IncrementVerificationCodeAttempts), ctx, id, maxAttempts)
	return &MockRepositoryIncrementVerificationCodeAttemptsCall{Call: call}
}

// MockRepositoryIncrementVerificationCodeAttemptsCall wrap *gomock.Call
type MockRepositoryIncrementVerificationCodeAttemptsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryIncrementVerificationCodeAttemptsCall) Return(arg0 int32, arg1 error) *MockRepositoryIncrementVerificationCodeAttemptsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryIncrementVerificationCodeAttemptsCall) Do(f func(context.Context, uuid.UUID, int32) (int32, error)) *MockRepositoryIncrementVerificationCodeAttemptsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryIncrementVerificationCodeAttemptsCall) DoAndReturn(f func(context.Context, uuid.UUID, int32) (int32, error)) *MockRepositoryIncrementVerificationCodeAttemptsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IssueVerificationCode mocks base method.
func (m *MockRepository) IssueVerificationCode(ctx context.Context, params registration.IssueVerificationCodeParams) (registrationdb.VerificationRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueVerificationCode", ctx, params)
	ret0, _ := ret[0].(registrationdb.VerificationRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueVerificationCode indicates an expected call of IssueVerificationCode.
func (mr *MockRepositoryMockRecorder) IssueVerificationCode(ctx, params any) *MockRepositoryIssueVerificationCodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueVerificationCode", reflect.TypeOf((*MockRepository)(nil).IssueVerificationCode), ctx, params)
	return &MockRepositoryIssueVerificationCodeCall{Call: call}
}

// MockRepositoryIssueVerificationCodeCall wrap *gomock.Call
type MockRepositoryIssueVerificationCodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryIssueVerificationCodeCall) Return(arg0 registrationdb.VerificationRequest, arg1 error) *MockRepositoryIssueVerificationCodeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryIssueVerificationCodeCall) Do(f func(context.Context, registration.IssueVerificationCodeParams) (registrationdb.VerificationRequest, error)) *MockRepositoryIssueVerificationCodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryIssueVerificationCodeCall) DoAndReturn(f func(context.Context, registration.IssueVerificationCodeParams) (registrationdb.VerificationRequest, error)) *MockRepositoryIssueVerificationCodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
