// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\api\auth\registration\service.go
//
// Generated by this command:
//
//	mockgen -typed -source .\internal\api\auth\registration\service.go -destination .\internal\api\auth\registration\mocks\service.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	registration "github.com/thoriqr/stash-it-backend/internal/api/auth/registration"
	gomock "go.uber.org/mock/gomock"
)

// MockSocialRegistrationService is a mock of SocialRegistrationService interface.
type MockSocialRegistrationService struct {
	ctrl     *gomock.Controller
	recorder *MockSocialRegistrationServiceMockRecorder
	isgomock struct{}
}

// MockSocialRegistrationServiceMockRecorder is the mock recorder for MockSocialRegistrationService.
type MockSocialRegistrationServiceMockRecorder struct {
	mock *MockSocialRegistrationService
}

// NewMockSocialRegistrationService creates a new mock instance.
func NewMockSocialRegistrationService(ctrl *gomock.Controller) *MockSocialRegistrationService {
	mock := &MockSocialRegistrationService{ctrl: ctrl}
	mock.recorder = &MockSocialRegistrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocialRegistrationService) EXPECT() *MockSocialRegistrationServiceMockRecorder {
	return m.recorder
}

// CreateSocialRegistration mocks base method.
func (m *MockSocialRegistrationService) CreateSocialRegistration(ctx context.Context, params registration.CreateSocialRegistrationInput) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSocialRegistration", ctx, params)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSocialRegistration indicates an expected call of CreateSocialRegistration.
func (mr *MockSocialRegistrationServiceMockRecorder) CreateSocialRegistration(ctx, params any) *MockSocialRegistrationServiceCreateSocialRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSocialRegistration", reflect.TypeOf((*MockSocialRegistrationService)(nil).CreateSocialRegistration), ctx, params)
	return &MockSocialRegistrationServiceCreateSocialRegistrationCall{Call: call}
}

// MockSocialRegistrationServiceCreateSocialRegistrationCall wrap *gomock.Call
type MockSocialRegistrationServiceCreateSocialRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSocialRegistrationServiceCreateSocialRegistrationCall) Return(arg0 uuid.UUID, arg1 error) *MockSocialRegistrationServiceCreateSocialRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSocialRegistrationServiceCreateSocialRegistrationCall) Do(f func(context.Context, registration.CreateSocialRegistrationInput) (uuid.UUID, error)) *MockSocialRegistrationServiceCreateSocialRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSocialRegistrationServiceCreateSocialRegistrationCall) DoAndReturn(f func(context.Context, registration.CreateSocialRegistrationInput) (uuid.UUID, error)) *MockSocialRegistrationServiceCreateSocialRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRegistrationService is a mock of RegistrationService interface.
type MockRegistrationService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationServiceMockRecorder
	isgomock struct{}
}

// MockRegistrationServiceMockRecorder is the mock recorder for MockRegistrationService.
type MockRegistrationServiceMockRecorder struct {
	mock *MockRegistrationService
}

// NewMockRegistrationService creates a new mock instance.
func NewMockRegistrationService(ctrl *gomock.Controller) *MockRegistrationService {
	mock := &MockRegistrationService{ctrl: ctrl}
	mock.recorder = &MockRegistrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationService) EXPECT() *MockRegistrationServiceMockRecorder {
	return m.recorder
}

// CreatePIN mocks base method.
func (m *MockRegistrationService) CreatePIN(ctx context.Context, verificationID uuid.UUID) (registration.CreatePINResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePIN", ctx, verificationID)
	ret0, _ := ret[0].(registration.CreatePINResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePIN indicates an expected call of CreatePIN.
func (mr *MockRegistrationServiceMockRecorder) CreatePIN(ctx, verificationID any) *MockRegistrationServiceCreatePINCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePIN", reflect.TypeOf((*MockRegistrationService)(nil).CreatePIN), ctx, verificationID)
	return &MockRegistrationServiceCreatePINCall{Call: call}
}

// MockRegistrationServiceCreatePINCall wrap *gomock.Call
type MockRegistrationServiceCreatePINCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationServiceCreatePINCall) Return(arg0 registration.CreatePINResult, arg1 error) *MockRegistrationServiceCreatePINCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationServiceCreatePINCall) Do(f func(context.Context, uuid.UUID) (registration.CreatePINResult, error)) *MockRegistrationServiceCreatePINCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationServiceCreatePINCall) DoAndReturn(f func(context.Context, uuid.UUID) (registration.CreatePINResult, error)) *MockRegistrationServiceCreatePINCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FinalizeManualRegistration mocks base method.
func (m *MockRegistrationService) FinalizeManualRegistration(ctx context.Context, params registration.FinalizeManualRegistrationInput) (registration.FinalizeManualRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeManualRegistration", ctx, params)
	ret0, _ := ret[0].(registration.FinalizeManualRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeManualRegistration indicates an expected call of FinalizeManualRegistration.
func (mr *MockRegistrationServiceMockRecorder) FinalizeManualRegistration(ctx, params any) *MockRegistrationServiceFinalizeManualRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeManualRegistration", reflect.TypeOf((*MockRegistrationService)(nil).FinalizeManualRegistration), ctx, params)
	return &MockRegistrationServiceFinalizeManualRegistrationCall{Call: call}
}

// MockRegistrationServiceFinalizeManualRegistrationCall wrap *gomock.Call
type MockRegistrationServiceFinalizeManualRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationServiceFinalizeManualRegistrationCall) Return(arg0 registration.FinalizeManualRegistrationResult, arg1 error) *MockRegistrationServiceFinalizeManualRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationServiceFinalizeManualRegistrationCall) Do(f func(context.Context, registration.FinalizeManualRegistrationInput) (registration.FinalizeManualRegistrationResult, error)) *MockRegistrationServiceFinalizeManualRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationServiceFinalizeManualRegistrationCall) DoAndReturn(f func(context.Context, registration.FinalizeManualRegistrationInput) (registration.FinalizeManualRegistrationResult, error)) *MockRegistrationServiceFinalizeManualRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FinalizeSocialRegistration mocks base method.
func (m *MockRegistrationService) FinalizeSocialRegistration(ctx context.Context, params registration.FinalizeSocialRegistrationInput) (registration.FinalizeSocialRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeSocialRegistration", ctx, params)
	ret0, _ := ret[0].(registration.FinalizeSocialRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeSocialRegistration indicates an expected call of FinalizeSocialRegistration.
func (mr *MockRegistrationServiceMockRecorder) FinalizeSocialRegistration(ctx, params any) *MockRegistrationServiceFinalizeSocialRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeSocialRegistration", reflect.TypeOf((*MockRegistrationService)(nil).FinalizeSocialRegistration), ctx, params)
	return &MockRegistrationServiceFinalizeSocialRegistrationCall{Call: call}
}

// MockRegistrationServiceFinalizeSocialRegistrationCall wrap *gomock.Call
type MockRegistrationServiceFinalizeSocialRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationServiceFinalizeSocialRegistrationCall) Return(arg0 registration.FinalizeSocialRegistrationResult, arg1 error) *MockRegistrationServiceFinalizeSocialRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationServiceFinalizeSocialRegistrationCall) Do(f func(context.Context, registration.FinalizeSocialRegistrationInput) (registration.FinalizeSocialRegistrationResult, error)) *MockRegistrationServiceFinalizeSocialRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationServiceFinalizeSocialRegistrationCall) DoAndReturn(f func(context.Context, registration.FinalizeSocialRegistrationInput) (registration.FinalizeSocialRegistrationResult, error)) *MockRegistrationServiceFinalizeSocialRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRegistrationContinuation mocks base method.
func (m *MockRegistrationService) GetRegistrationContinuation(ctx context.Context, token string) (registration.GetRegistrationContinuationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationContinuation", ctx, token)
	ret0, _ := ret[0].(registration.GetRegistrationContinuationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationContinuation indicates an expected call of GetRegistrationContinuation.
func (mr *MockRegistrationServiceMockRecorder) GetRegistrationContinuation(ctx, token any) *MockRegistrationServiceGetRegistrationContinuationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationContinuation", reflect.TypeOf((*MockRegistrationService)(nil).GetRegistrationContinuation), ctx, token)
	return &MockRegistrationServiceGetRegistrationContinuationCall{Call: call}
}

// MockRegistrationServiceGetRegistrationContinuationCall wrap *gomock.Call
type MockRegistrationServiceGetRegistrationContinuationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationServiceGetRegistrationContinuationCall) Return(arg0 registration.GetRegistrationContinuationResult, arg1 error) *MockRegistrationServiceGetRegistrationContinuationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationServiceGetRegistrationContinuationCall) Do(f func(context.Context, string) (registration.GetRegistrationContinuationResult, error)) *MockRegistrationServiceGetRegistrationContinuationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationServiceGetRegistrationContinuationCall) DoAndReturn(f func(context.Context, string) (registration.GetRegistrationContinuationResult, error)) *MockRegistrationServiceGetRegistrationContinuationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetVerification mocks base method.
func (m *MockRegistrationService) GetVerification(ctx context.Context, verificationID uuid.UUID) (registration.GetVerificationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerification", ctx, verificationID)
	ret0, _ := ret[0].(registration.GetVerificationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerification indicates an expected call of GetVerification.
func (mr *MockRegistrationServiceMockRecorder) GetVerification(ctx, verificationID any) *MockRegistrationServiceGetVerificationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerification", reflect.TypeOf((*MockRegistrationService)(nil).GetVerification), ctx, verificationID)
	return &MockRegistrationServiceGetVerificationCall{Call: call}
}

// MockRegistrationServiceGetVerificationCall wrap *gomock.Call
type MockRegistrationServiceGetVerificationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationServiceGetVerificationCall) Return(arg0 registration.GetVerificationResult, arg1 error) *MockRegistrationServiceGetVerificationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationServiceGetVerificationCall) Do(f func(context.Context, uuid.UUID) (registration.GetVerificationResult, error)) *MockRegistrationServiceGetVerificationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationServiceGetVerificationCall) DoAndReturn(f func(context.Context, uuid.UUID) (registration.GetVerificationResult, error)) *MockRegistrationServiceGetVerificationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterManual mocks base method.
func (m *MockRegistrationService) RegisterManual(ctx context.Context, email string) (registration.RegisterManualResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterManual", ctx, email)
	ret0, _ := ret[0].(registration.RegisterManualResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterManual indicates an expected call of RegisterManual.
func (mr *MockRegistrationServiceMockRecorder) RegisterManual(ctx, email any) *MockRegistrationServiceRegisterManualCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterManual", reflect.TypeOf((*MockRegistrationService)(nil).RegisterManual), ctx, email)
	return &MockRegistrationServiceRegisterManualCall{Call: call}
}

// MockRegistrationServiceRegisterManualCall wrap *gomock.Call
type MockRegistrationServiceRegisterManualCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationServiceRegisterManualCall) Return(arg0 registration.RegisterManualResult, arg1 error) *MockRegistrationServiceRegisterManualCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationServiceRegisterManualCall) Do(f func(context.Context, string) (registration.RegisterManualResult, error)) *MockRegistrationServiceRegisterManualCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationServiceRegisterManualCall) DoAndReturn(f func(context.Context, string) (registration.RegisterManualResult, error)) *MockRegistrationServiceRegisterManualCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResendVerification mocks base method.
func (m *MockRegistrationService) ResendVerification(ctx context.Context, verificationID uuid.UUID) (registration.ResendVerificationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendVerification", ctx, verificationID)
	ret0, _ := ret[0].(registration.ResendVerificationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResendVerification indicates an expected call of ResendVerification.
func (mr *MockRegistrationServiceMockRecorder) ResendVerification(ctx, verificationID any) *MockRegistrationServiceResendVerificationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendVerification", reflect.TypeOf((*MockRegistrationService)(nil).ResendVerification), ctx, verificationID)
	return &MockRegistrationServiceResendVerificationCall{Call: call}
}

// MockRegistrationServiceResendVerificationCall wrap *gomock.Call
type MockRegistrationServiceResendVerificationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationServiceResendVerificationCall) Return(arg0 registration.ResendVerificationResult, arg1 error) *MockRegistrationServiceResendVerificationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationServiceResendVerificationCall) Do(f func(context.Context, uuid.UUID) (registration.ResendVerificationResult, error)) *MockRegistrationServiceResendVerificationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationServiceResendVerificationCall) DoAndReturn(f func(context.Context, uuid.UUID) (registration.ResendVerificationResult, error)) *MockRegistrationServiceResendVerificationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VerifyRegistration mocks base method.
func (m *MockRegistrationService) VerifyRegistration(ctx context.Context, verificationID uuid.UUID, pin string) (registration.VerifyRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRegistration", ctx, verificationID, pin)
	ret0, _ := ret[0].(registration.VerifyRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRegistration indicates an expected call of VerifyRegistration.
func (mr *MockRegistrationServiceMockRecorder) VerifyRegistration(ctx, verificationID, pin any) *MockRegistrationServiceVerifyRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRegistration", reflect.TypeOf((*MockRegistrationService)(nil).VerifyRegistration), ctx, verificationID, pin)
	return &MockRegistrationServiceVerifyRegistrationCall{Call: call}
}

// MockRegistrationServiceVerifyRegistrationCall wrap *gomock.Call
type MockRegistrationServiceVerifyRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistrationServiceVerifyRegistrationCall) Return(arg0 registration.VerifyRegistrationResult, arg1 error) *MockRegistrationServiceVerifyRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistrationServiceVerifyRegistrationCall) Do(f func(context.Context, uuid.UUID, string) (registration.VerifyRegistrationResult, error)) *MockRegistrationServiceVerifyRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistrationServiceVerifyRegistrationCall) DoAndReturn(f func(context.Context, uuid.UUID, string) (registration.VerifyRegistrationResult, error)) *MockRegistrationServiceVerifyRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
