// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/enrichment/types.go
//
// Generated by this command:
//
//	mockgen -typed -source internal/api/enrichment/types.go -destination internal/api/enrichment/mocks/enricher.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	enrichment "github.com/thoriqr/stash-it-backend/internal/enrichment"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataEnricher is a mock of MetadataEnricher interface.
type MockMetadataEnricher struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataEnricherMockRecorder
	isgomock struct{}
}

// MockMetadataEnricherMockRecorder is the mock recorder for MockMetadataEnricher.
type MockMetadataEnricherMockRecorder struct {
	mock *MockMetadataEnricher
}

// NewMockMetadataEnricher creates a new mock instance.
func NewMockMetadataEnricher(ctrl *gomock.Controller) *MockMetadataEnricher {
	mock := &MockMetadataEnricher{ctrl: ctrl}
	mock.recorder = &MockMetadataEnricherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataEnricher) EXPECT() *MockMetadataEnricherMockRecorder {
	return m.recorder
}

// Enrich mocks base method.
func (m *MockMetadataEnricher) Enrich(ctx context.Context, rawURL string) (enrichment.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrich", ctx, rawURL)
	ret0, _ := ret[0].(enrichment.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enrich indicates an expected call of Enrich.
func (mr *MockMetadataEnricherMockRecorder) Enrich(ctx, rawURL any) *MockMetadataEnricherEnrichCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrich", reflect.TypeOf((*MockMetadataEnricher)(nil).Enrich), ctx, rawURL)
	return &MockMetadataEnricherEnrichCall{Call: call}
}

// MockMetadataEnricherEnrichCall wrap *gomock.Call
type MockMetadataEnricherEnrichCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetadataEnricherEnrichCall) Return(arg0 enrichment.Metadata, arg1 error) *MockMetadataEnricherEnrichCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetadataEnricherEnrichCall) Do(f func(context.Context, string) (enrichment.Metadata, error)) *MockMetadataEnricherEnrichCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetadataEnricherEnrichCall) DoAndReturn(f func(context.Context, string) (enrichment.Metadata, error)) *MockMetadataEnricherEnrichCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
