// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/enrichment/repository.go
//
// Generated by this command:
//
//	mockgen -typed -source internal/api/enrichment/repository.go -destination internal/api/enrichment/mocks/repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	enrichment "github.com/thoriqr/stash-it-backend/internal/api/enrichment"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CompleteSavedItemEnrichment mocks base method.
func (m *MockRepository) CompleteSavedItemEnrichment(ctx context.Context, params enrichment.CompleteSavedItemEnrichmentParams) (enrichment.SavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSavedItemEnrichment", ctx, params)
	ret0, _ := ret[0].(enrichment.SavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteSavedItemEnrichment indicates an expected call of CompleteSavedItemEnrichment.
func (mr *MockRepositoryMockRecorder) CompleteSavedItemEnrichment(ctx, params any) *MockRepositoryCompleteSavedItemEnrichmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSavedItemEnrichment", reflect.TypeOf((*MockRepository)(nil).CompleteSavedItemEnrichment), ctx, params)
	return &MockRepositoryCompleteSavedItemEnrichmentCall{Call: call}
}

// MockRepositoryCompleteSavedItemEnrichmentCall wrap *gomock.Call
type MockRepositoryCompleteSavedItemEnrichmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCompleteSavedItemEnrichmentCall) Return(arg0 enrichment.SavedItem, arg1 error) *MockRepositoryCompleteSavedItemEnrichmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCompleteSavedItemEnrichmentCall) Do(f func(context.Context, enrichment.CompleteSavedItemEnrichmentParams) (enrichment.SavedItem, error)) *MockRepositoryCompleteSavedItemEnrichmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCompleteSavedItemEnrichmentCall) DoAndReturn(f func(context.Context, enrichment.CompleteSavedItemEnrichmentParams) (enrichment.SavedItem, error)) *MockRepositoryCompleteSavedItemEnrichmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FailSavedItemEnrichment mocks base method.
func (m *MockRepository) FailSavedItemEnrichment(ctx context.Context, userID, savedItemID uuid.UUID) (enrichment.SavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailSavedItemEnrichment", ctx, userID, savedItemID)
	ret0, _ := ret[0].(enrichment.SavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FailSavedItemEnrichment indicates an expected call of FailSavedItemEnrichment.
func (mr *MockRepositoryMockRecorder) FailSavedItemEnrichment(ctx, userID, savedItemID any) *MockRepositoryFailSavedItemEnrichmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailSavedItemEnrichment", reflect.TypeOf((*MockRepository)(nil).FailSavedItemEnrichment), ctx, userID, savedItemID)
	return &MockRepositoryFailSavedItemEnrichmentCall{Call: call}
}

// MockRepositoryFailSavedItemEnrichmentCall wrap *gomock.Call
type MockRepositoryFailSavedItemEnrichmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFailSavedItemEnrichmentCall) Return(arg0 enrichment.SavedItem, arg1 error) *MockRepositoryFailSavedItemEnrichmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFailSavedItemEnrichmentCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) (enrichment.SavedItem, error)) *MockRepositoryFailSavedItemEnrichmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFailSavedItemEnrichmentCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) (enrichment.SavedItem, error)) *MockRepositoryFailSavedItemEnrichmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSavedItemURLForEnrichment mocks base method.
func (m *MockRepository) GetSavedItemURLForEnrichment(ctx context.Context, userID, savedItemID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavedItemURLForEnrichment", ctx, userID, savedItemID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSavedItemURLForEnrichment indicates an expected call of GetSavedItemURLForEnrichment.
func (mr *MockRepositoryMockRecorder) GetSavedItemURLForEnrichment(ctx, userID, savedItemID any) *MockRepositoryGetSavedItemURLForEnrichmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavedItemURLForEnrichment", reflect.TypeOf((*MockRepository)(nil).GetSavedItemURLForEnrichment), ctx, userID, savedItemID)
	return &MockRepositoryGetSavedItemURLForEnrichmentCall{Call: call}
}

// MockRepositoryGetSavedItemURLForEnrichmentCall wrap *gomock.Call
type MockRepositoryGetSavedItemURLForEnrichmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetSavedItemURLForEnrichmentCall) Return(arg0 string, arg1 error) *MockRepositoryGetSavedItemURLForEnrichmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetSavedItemURLForEnrichmentCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) (string, error)) *MockRepositoryGetSavedItemURLForEnrichmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetSavedItemURLForEnrichmentCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) (string, error)) *MockRepositoryGetSavedItemURLForEnrichmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
