// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/search/repository.go
//
// Generated by this command:
//
//	mockgen -typed -source internal/api/search/repository.go -destination internal/api/search/mocks/repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	search "github.com/thoriqr/stash-it-backend/internal/api/search"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// SearchCollections mocks base method.
func (m *MockRepository) SearchCollections(ctx context.Context, params search.SearchCollectionsParams) ([]search.SearchCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCollections", ctx, params)
	ret0, _ := ret[0].([]search.SearchCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCollections indicates an expected call of SearchCollections.
func (mr *MockRepositoryMockRecorder) SearchCollections(ctx, params any) *MockRepositorySearchCollectionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCollections", reflect.TypeOf((*MockRepository)(nil).SearchCollections), ctx, params)
	return &MockRepositorySearchCollectionsCall{Call: call}
}

// MockRepositorySearchCollectionsCall wrap *gomock.Call
type MockRepositorySearchCollectionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositorySearchCollectionsCall) Return(arg0 []search.SearchCollection, arg1 error) *MockRepositorySearchCollectionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositorySearchCollectionsCall) Do(f func(context.Context, search.SearchCollectionsParams) ([]search.SearchCollection, error)) *MockRepositorySearchCollectionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositorySearchCollectionsCall) DoAndReturn(f func(context.Context, search.SearchCollectionsParams) ([]search.SearchCollection, error)) *MockRepositorySearchCollectionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SearchSavedItems mocks base method.
func (m *MockRepository) SearchSavedItems(ctx context.Context, params search.SearchSavedItemsParams) ([]search.SearchSavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSavedItems", ctx, params)
	ret0, _ := ret[0].([]search.SearchSavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSavedItems indicates an expected call of SearchSavedItems.
func (mr *MockRepositoryMockRecorder) SearchSavedItems(ctx, params any) *MockRepositorySearchSavedItemsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSavedItems", reflect.TypeOf((*MockRepository)(nil).SearchSavedItems), ctx, params)
	return &MockRepositorySearchSavedItemsCall{Call: call}
}

// MockRepositorySearchSavedItemsCall wrap *gomock.Call
type MockRepositorySearchSavedItemsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositorySearchSavedItemsCall) Return(arg0 []search.SearchSavedItem, arg1 error) *MockRepositorySearchSavedItemsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositorySearchSavedItemsCall) Do(f func(context.Context, search.SearchSavedItemsParams) ([]search.SearchSavedItem, error)) *MockRepositorySearchSavedItemsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositorySearchSavedItemsCall) DoAndReturn(f func(context.Context, search.SearchSavedItemsParams) ([]search.SearchSavedItem, error)) *MockRepositorySearchSavedItemsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
