// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/saved_item/enqueuer.go
//
// Generated by this command:
//
//	mockgen -typed -source internal/api/saved_item/enqueuer.go -destination internal/api/saved_item/mocks/enqueuer.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSavedItemEnqueuer is a mock of SavedItemEnqueuer interface.
type MockSavedItemEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockSavedItemEnqueuerMockRecorder
	isgomock struct{}
}

// MockSavedItemEnqueuerMockRecorder is the mock recorder for MockSavedItemEnqueuer.
type MockSavedItemEnqueuerMockRecorder struct {
	mock *MockSavedItemEnqueuer
}

// NewMockSavedItemEnqueuer creates a new mock instance.
func NewMockSavedItemEnqueuer(ctrl *gomock.Controller) *MockSavedItemEnqueuer {
	mock := &MockSavedItemEnqueuer{ctrl: ctrl}
	mock.recorder = &MockSavedItemEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSavedItemEnqueuer) EXPECT() *MockSavedItemEnqueuerMockRecorder {
	return m.recorder
}

// EnqueueSavedItemEnrichment mocks base method.
func (m *MockSavedItemEnqueuer) EnqueueSavedItemEnrichment(ctx context.Context, savedItemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueSavedItemEnrichment", ctx, savedItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueSavedItemEnrichment indicates an expected call of EnqueueSavedItemEnrichment.
func (mr *MockSavedItemEnqueuerMockRecorder) EnqueueSavedItemEnrichment(ctx, savedItemID any) *MockSavedItemEnqueuerEnqueueSavedItemEnrichmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueSavedItemEnrichment", reflect.TypeOf((*MockSavedItemEnqueuer)(nil).EnqueueSavedItemEnrichment), ctx, savedItemID)
	return &MockSavedItemEnqueuerEnqueueSavedItemEnrichmentCall{Call: call}
}

// MockSavedItemEnqueuerEnqueueSavedItemEnrichmentCall wrap *gomock.Call
type MockSavedItemEnqueuerEnqueueSavedItemEnrichmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSavedItemEnqueuerEnqueueSavedItemEnrichmentCall) Return(arg0 error) *MockSavedItemEnqueuerEnqueueSavedItemEnrichmentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSavedItemEnqueuerEnqueueSavedItemEnrichmentCall) Do(f func(context.Context, uuid.UUID) error) *MockSavedItemEnqueuerEnqueueSavedItemEnrichmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSavedItemEnqueuerEnqueueSavedItemEnrichmentCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockSavedItemEnqueuerEnqueueSavedItemEnrichmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
