// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/saved_item/repository.go
//
// Generated by this command:
//
//	mockgen -typed -source internal/api/saved_item/repository.go -destination internal/api/saved_item/mocks/repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	saved_item "github.com/thoriqr/stash-it-backend/internal/api/saved_item"
	saveditemdb "github.com/thoriqr/stash-it-backend/internal/api/saved_item/generated"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountSavedItemsInCollection mocks base method.
func (m *MockRepository) CountSavedItemsInCollection(ctx context.Context, userID, collectionID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSavedItemsInCollection", ctx, userID, collectionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSavedItemsInCollection indicates an expected call of CountSavedItemsInCollection.
func (mr *MockRepositoryMockRecorder) CountSavedItemsInCollection(ctx, userID, collectionID any) *MockRepositoryCountSavedItemsInCollectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSavedItemsInCollection", reflect.TypeOf((*MockRepository)(nil).CountSavedItemsInCollection), ctx, userID, collectionID)
	return &MockRepositoryCountSavedItemsInCollectionCall{Call: call}
}

// MockRepositoryCountSavedItemsInCollectionCall wrap *gomock.Call
type MockRepositoryCountSavedItemsInCollectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCountSavedItemsInCollectionCall) Return(arg0 int64, arg1 error) *MockRepositoryCountSavedItemsInCollectionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCountSavedItemsInCollectionCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) (int64, error)) *MockRepositoryCountSavedItemsInCollectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCountSavedItemsInCollectionCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) (int64, error)) *MockRepositoryCountSavedItemsInCollectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSavedItem mocks base method.
func (m *MockRepository) CreateSavedItem(ctx context.Context, params saveditemdb.CreateSavedItemParams) (saved_item.SavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSavedItem", ctx, params)
	ret0, _ := ret[0].(saved_item.SavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSavedItem indicates an expected call of CreateSavedItem.
func (mr *MockRepositoryMockRecorder) CreateSavedItem(ctx, params any) *MockRepositoryCreateSavedItemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSavedItem", reflect.TypeOf((*MockRepository)(nil).CreateSavedItem), ctx, params)
	return &MockRepositoryCreateSavedItemCall{Call: call}
}

// MockRepositoryCreateSavedItemCall wrap *gomock.Call
type MockRepositoryCreateSavedItemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateSavedItemCall) Return(arg0 saved_item.SavedItem, arg1 error) *MockRepositoryCreateSavedItemCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateSavedItemCall) Do(f func(context.Context, saveditemdb.CreateSavedItemParams) (saved_item.SavedItem, error)) *MockRepositoryCreateSavedItemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateSavedItemCall) DoAndReturn(f func(context.Context, saveditemdb.CreateSavedItemParams) (saved_item.SavedItem, error)) *MockRepositoryCreateSavedItemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteSavedItemByIDForUser mocks base method.
func (m *MockRepository) DeleteSavedItemByIDForUser(ctx context.Context, userID, savedItemID uuid.UUID) (saved_item.DeletedSavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSavedItemByIDForUser", ctx, userID, savedItemID)
	ret0, _ := ret[0].(saved_item.DeletedSavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSavedItemByIDForUser indicates an expected call of DeleteSavedItemByIDForUser.
func (mr *MockRepositoryMockRecorder) DeleteSavedItemByIDForUser(ctx, userID, savedItemID any) *MockRepositoryDeleteSavedItemByIDForUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSavedItemByIDForUser", reflect.TypeOf((*MockRepository)(nil).DeleteSavedItemByIDForUser), ctx, userID, savedItemID)
	return &MockRepositoryDeleteSavedItemByIDForUserCall{Call: call}
}

// MockRepositoryDeleteSavedItemByIDForUserCall wrap *gomock.Call
type MockRepositoryDeleteSavedItemByIDForUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDeleteSavedItemByIDForUserCall) Return(arg0 saved_item.DeletedSavedItem, arg1 error) *MockRepositoryDeleteSavedItemByIDForUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDeleteSavedItemByIDForUserCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) (saved_item.DeletedSavedItem, error)) *MockRepositoryDeleteSavedItemByIDForUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDeleteSavedItemByIDForUserCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) (saved_item.DeletedSavedItem, error)) *MockRepositoryDeleteSavedItemByIDForUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCollectionSystemKeyForUser mocks base method.
func (m *MockRepository) GetCollectionSystemKeyForUser(ctx context.Context, userID, collectionID uuid.UUID) (pgtype.Text, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionSystemKeyForUser", ctx, userID, collectionID)
	ret0, _ := ret[0].(pgtype.Text)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionSystemKeyForUser indicates an expected call of GetCollectionSystemKeyForUser.
func (mr *MockRepositoryMockRecorder) GetCollectionSystemKeyForUser(ctx, userID, collectionID any) *MockRepositoryGetCollectionSystemKeyForUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionSystemKeyForUser", reflect.TypeOf((*MockRepository)(nil).GetCollectionSystemKeyForUser), ctx, userID, collectionID)
	return &MockRepositoryGetCollectionSystemKeyForUserCall{Call: call}
}

// MockRepositoryGetCollectionSystemKeyForUserCall wrap *gomock.Call
type MockRepositoryGetCollectionSystemKeyForUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetCollectionSystemKeyForUserCall) Return(arg0 pgtype.Text, arg1 error) *MockRepositoryGetCollectionSystemKeyForUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetCollectionSystemKeyForUserCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) (pgtype.Text, error)) *MockRepositoryGetCollectionSystemKeyForUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetCollectionSystemKeyForUserCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) (pgtype.Text, error)) *MockRepositoryGetCollectionSystemKeyForUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSavedItemByIDForUser mocks base method.
func (m *MockRepository) GetSavedItemByIDForUser(ctx context.Context, userID, savedItemID uuid.UUID) (saved_item.SavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavedItemByIDForUser", ctx, userID, savedItemID)
	ret0, _ := ret[0].(saved_item.SavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSavedItemByIDForUser indicates an expected call of GetSavedItemByIDForUser.
func (mr *MockRepositoryMockRecorder) GetSavedItemByIDForUser(ctx, userID, savedItemID any) *MockRepositoryGetSavedItemByIDForUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavedItemByIDForUser", reflect.TypeOf((*MockRepository)(nil).GetSavedItemByIDForUser), ctx, userID, savedItemID)
	return &MockRepositoryGetSavedItemByIDForUserCall{Call: call}
}

// MockRepositoryGetSavedItemByIDForUserCall wrap *gomock.Call
type MockRepositoryGetSavedItemByIDForUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetSavedItemByIDForUserCall) Return(arg0 saved_item.SavedItem, arg1 error) *MockRepositoryGetSavedItemByIDForUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetSavedItemByIDForUserCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) (saved_item.SavedItem, error)) *MockRepositoryGetSavedItemByIDForUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetSavedItemByIDForUserCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) (saved_item.SavedItem, error)) *MockRepositoryGetSavedItemByIDForUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUnsortedCollectionByUser mocks base method.
func (m *MockRepository) GetUnsortedCollectionByUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnsortedCollectionByUser", ctx, userID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnsortedCollectionByUser indicates an expected call of GetUnsortedCollectionByUser.
func (mr *MockRepositoryMockRecorder) GetUnsortedCollectionByUser(ctx, userID any) *MockRepositoryGetUnsortedCollectionByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnsortedCollectionByUser", reflect.TypeOf((*MockRepository)(nil).GetUnsortedCollectionByUser), ctx, userID)
	return &MockRepositoryGetUnsortedCollectionByUserCall{Call: call}
}

// MockRepositoryGetUnsortedCollectionByUserCall wrap *gomock.Call
type MockRepositoryGetUnsortedCollectionByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetUnsortedCollectionByUserCall) Return(arg0 uuid.UUID, arg1 error) *MockRepositoryGetUnsortedCollectionByUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetUnsortedCollectionByUserCall) Do(f func(context.Context, uuid.UUID) (uuid.UUID, error)) *MockRepositoryGetUnsortedCollectionByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetUnsortedCollectionByUserCall) DoAndReturn(f func(context.Context, uuid.UUID) (uuid.UUID, error)) *MockRepositoryGetUnsortedCollectionByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
