// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\api\saved_item\repository.go
//
// Generated by this command:
//
//	mockgen -typed -source .\internal\api\saved_item\repository.go -destination .\internal\api\saved_item\mocks\repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	saveditemdb "github.com/thoriqr/stash-it-backend/internal/api/saved_item/generated"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountSavedItems mocks base method.
func (m *MockRepository) CountSavedItems(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSavedItems", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSavedItems indicates an expected call of CountSavedItems.
func (mr *MockRepositoryMockRecorder) CountSavedItems(ctx, userID any) *MockRepositoryCountSavedItemsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSavedItems", reflect.TypeOf((*MockRepository)(nil).CountSavedItems), ctx, userID)
	return &MockRepositoryCountSavedItemsCall{Call: call}
}

// MockRepositoryCountSavedItemsCall wrap *gomock.Call
type MockRepositoryCountSavedItemsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCountSavedItemsCall) Return(arg0 int64, arg1 error) *MockRepositoryCountSavedItemsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCountSavedItemsCall) Do(f func(context.Context, uuid.UUID) (int64, error)) *MockRepositoryCountSavedItemsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCountSavedItemsCall) DoAndReturn(f func(context.Context, uuid.UUID) (int64, error)) *MockRepositoryCountSavedItemsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSavedItem mocks base method.
func (m *MockRepository) CreateSavedItem(ctx context.Context, params saveditemdb.CreateSavedItemParams) (saveditemdb.SavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSavedItem", ctx, params)
	ret0, _ := ret[0].(saveditemdb.SavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSavedItem indicates an expected call of CreateSavedItem.
func (mr *MockRepositoryMockRecorder) CreateSavedItem(ctx, params any) *MockRepositoryCreateSavedItemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSavedItem", reflect.TypeOf((*MockRepository)(nil).CreateSavedItem), ctx, params)
	return &MockRepositoryCreateSavedItemCall{Call: call}
}

// MockRepositoryCreateSavedItemCall wrap *gomock.Call
type MockRepositoryCreateSavedItemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateSavedItemCall) Return(arg0 saveditemdb.SavedItem, arg1 error) *MockRepositoryCreateSavedItemCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateSavedItemCall) Do(f func(context.Context, saveditemdb.CreateSavedItemParams) (saveditemdb.SavedItem, error)) *MockRepositoryCreateSavedItemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateSavedItemCall) DoAndReturn(f func(context.Context, saveditemdb.CreateSavedItemParams) (saveditemdb.SavedItem, error)) *MockRepositoryCreateSavedItemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteSavedItemByIDForUser mocks base method.
func (m *MockRepository) DeleteSavedItemByIDForUser(ctx context.Context, userID, savedItemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSavedItemByIDForUser", ctx, userID, savedItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSavedItemByIDForUser indicates an expected call of DeleteSavedItemByIDForUser.
func (mr *MockRepositoryMockRecorder) DeleteSavedItemByIDForUser(ctx, userID, savedItemID any) *MockRepositoryDeleteSavedItemByIDForUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSavedItemByIDForUser", reflect.TypeOf((*MockRepository)(nil).DeleteSavedItemByIDForUser), ctx, userID, savedItemID)
	return &MockRepositoryDeleteSavedItemByIDForUserCall{Call: call}
}

// MockRepositoryDeleteSavedItemByIDForUserCall wrap *gomock.Call
type MockRepositoryDeleteSavedItemByIDForUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDeleteSavedItemByIDForUserCall) Return(arg0 error) *MockRepositoryDeleteSavedItemByIDForUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDeleteSavedItemByIDForUserCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockRepositoryDeleteSavedItemByIDForUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDeleteSavedItemByIDForUserCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockRepositoryDeleteSavedItemByIDForUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSavedItemByIDForUser mocks base method.
func (m *MockRepository) GetSavedItemByIDForUser(ctx context.Context, userID, savedItemID uuid.UUID) (saveditemdb.SavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavedItemByIDForUser", ctx, userID, savedItemID)
	ret0, _ := ret[0].(saveditemdb.SavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSavedItemByIDForUser indicates an expected call of GetSavedItemByIDForUser.
func (mr *MockRepositoryMockRecorder) GetSavedItemByIDForUser(ctx, userID, savedItemID any) *MockRepositoryGetSavedItemByIDForUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavedItemByIDForUser", reflect.TypeOf((*MockRepository)(nil).GetSavedItemByIDForUser), ctx, userID, savedItemID)
	return &MockRepositoryGetSavedItemByIDForUserCall{Call: call}
}

// MockRepositoryGetSavedItemByIDForUserCall wrap *gomock.Call
type MockRepositoryGetSavedItemByIDForUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetSavedItemByIDForUserCall) Return(arg0 saveditemdb.SavedItem, arg1 error) *MockRepositoryGetSavedItemByIDForUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetSavedItemByIDForUserCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) (saveditemdb.SavedItem, error)) *MockRepositoryGetSavedItemByIDForUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetSavedItemByIDForUserCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) (saveditemdb.SavedItem, error)) *MockRepositoryGetSavedItemByIDForUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSavedItems mocks base method.
func (m *MockRepository) ListSavedItems(ctx context.Context, userID uuid.UUID, offset, limit int32) ([]saveditemdb.SavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSavedItems", ctx, userID, offset, limit)
	ret0, _ := ret[0].([]saveditemdb.SavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSavedItems indicates an expected call of ListSavedItems.
func (mr *MockRepositoryMockRecorder) ListSavedItems(ctx, userID, offset, limit any) *MockRepositoryListSavedItemsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSavedItems", reflect.TypeOf((*MockRepository)(nil).ListSavedItems), ctx, userID, offset, limit)
	return &MockRepositoryListSavedItemsCall{Call: call}
}

// MockRepositoryListSavedItemsCall wrap *gomock.Call
type MockRepositoryListSavedItemsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListSavedItemsCall) Return(arg0 []saveditemdb.SavedItem, arg1 error) *MockRepositoryListSavedItemsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListSavedItemsCall) Do(f func(context.Context, uuid.UUID, int32, int32) ([]saveditemdb.SavedItem, error)) *MockRepositoryListSavedItemsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListSavedItemsCall) DoAndReturn(f func(context.Context, uuid.UUID, int32, int32) ([]saveditemdb.SavedItem, error)) *MockRepositoryListSavedItemsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
