// Code generated by MockGen. DO NOT EDIT.
// Source: internal\worker\organization\repository.go
//
// Generated by this command:
//
//	mockgen -typed -source internal\worker\organization\repository.go -destination internal\worker\organization\mocks\repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	organization "github.com/thoriqr/stash-it-backend/internal/worker/organization"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// OrganizeSavedItem mocks base method.
func (m *MockRepository) OrganizeSavedItem(ctx context.Context, savedItemID, userID uuid.UUID) (organization.Outcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizeSavedItem", ctx, savedItemID, userID)
	ret0, _ := ret[0].(organization.Outcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrganizeSavedItem indicates an expected call of OrganizeSavedItem.
func (mr *MockRepositoryMockRecorder) OrganizeSavedItem(ctx, savedItemID, userID any) *MockRepositoryOrganizeSavedItemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizeSavedItem", reflect.TypeOf((*MockRepository)(nil).OrganizeSavedItem), ctx, savedItemID, userID)
	return &MockRepositoryOrganizeSavedItemCall{Call: call}
}

// MockRepositoryOrganizeSavedItemCall wrap *gomock.Call
type MockRepositoryOrganizeSavedItemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryOrganizeSavedItemCall) Return(arg0 organization.Outcome, arg1 error) *MockRepositoryOrganizeSavedItemCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryOrganizeSavedItemCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) (organization.Outcome, error)) *MockRepositoryOrganizeSavedItemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryOrganizeSavedItemCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) (organization.Outcome, error)) *MockRepositoryOrganizeSavedItemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
