// Code generated by MockGen. DO NOT EDIT.
// Source: internal\worker\organization\service.go
//
// Generated by this command:
//
//	mockgen -typed -source internal\worker\organization\service.go -destination internal\worker\organization\mocks\service.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// OrganizeSavedItem mocks base method.
func (m *MockService) OrganizeSavedItem(ctx context.Context, savedItemID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizeSavedItem", ctx, savedItemID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OrganizeSavedItem indicates an expected call of OrganizeSavedItem.
func (mr *MockServiceMockRecorder) OrganizeSavedItem(ctx, savedItemID, userID any) *MockServiceOrganizeSavedItemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizeSavedItem", reflect.TypeOf((*MockService)(nil).OrganizeSavedItem), ctx, savedItemID, userID)
	return &MockServiceOrganizeSavedItemCall{Call: call}
}

// MockServiceOrganizeSavedItemCall wrap *gomock.Call
type MockServiceOrganizeSavedItemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceOrganizeSavedItemCall) Return(arg0 error) *MockServiceOrganizeSavedItemCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceOrganizeSavedItemCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockServiceOrganizeSavedItemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceOrganizeSavedItemCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockServiceOrganizeSavedItemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
