// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register/continuation": {
            "get": {
                "description": "Validate and retrieve the registration continuation associated with the continuation token.\nPossible error codes:\n- REGISTRATION_CONTINUATION_REQUIRED\n- REGISTRATION_CONTINUATION_CONSUMED\n- REGISTRATION_CONTINUATION_EXPIRED\n- REGISTRATION_NOT_PENDING\n- REGISTRATION_EXPIRED\n- INTERNAL_SERVER_ERROR",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get registration continuation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Registration continuation token",
                        "name": "X-Registration-Continuation",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.GetRegistrationContinuationAPIResponse"
                        }
                    },
                    "401": {
                        "description": "Registration continuation token is required",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Registration continuation is invalid or expired",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register/finalize/manual": {
            "post": {
                "description": "Complete a manual registration using a valid registration continuation token.\nPossible error codes:\n- REGISTRATION_CONTINUATION_CONSUMED\n- REGISTRATION_CONTINUATION_EXPIRED\n- REGISTRATION_NOT_PENDING\n- REGISTRATION_EXPIRED\n- INVALID_REGISTRATION_TYPE\n- USER_ALREADY_EXISTS\n- INTERNAL_SERVER_ERROR",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Finalize manual registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Registration continuation token",
                        "name": "X-Registration-Continuation",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Finalize registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/registration.FinalizeManualRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/registration.FinalizeManualRegistrationAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Registration continuation token is required",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Registration cannot be finalized",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register/finalize/social": {
            "post": {
                "description": "Complete a social registration using a valid registration continuation token and create an authenticated session.\nPossible error codes:\n- REGISTRATION_CONTINUATION_CONSUMED\n- REGISTRATION_CONTINUATION_EXPIRED\n- REGISTRATION_NOT_PENDING\n- REGISTRATION_EXPIRED\n- INVALID_REGISTRATION_TYPE\n- USER_ALREADY_EXISTS\n- AUTH_IDENTITY_ALREADY_EXISTS\n- INTERNAL_SERVER_ERROR",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Finalize social registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Registration continuation token",
                        "name": "X-Registration-Continuation",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client platform",
                        "name": "X-Platform",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Client installation ID (UUID)",
                        "name": "X-Installation-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Client device name",
                        "name": "X-Device-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Client user agent",
                        "name": "User-Agent",
                        "in": "header"
                    },
                    {
                        "description": "Finalize social registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/registration.FinalizeSocialRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/registration.FinalizeSocialRegistrationAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Registration continuation token is required",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Registration cannot be finalized",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register/manual": {
            "post": {
                "description": "Start a manual registration flow using an email address.\nPossible error codes:\n- VALIDATION_ERROR\n- REGISTRATION_ALREADY_COMPLETED\n- REGISTRATION_ALREADY_EXISTS\n- INTERNAL_SERVER_ERROR",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register with email",
                "parameters": [
                    {
                        "description": "Registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/registration.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/registration.RegisterAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/swagger.ValidationErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Registration conflict",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register/verification/{verification_id}": {
            "get": {
                "description": "Get the current status of a registration verification request.\nPossible error codes:\n- BAD_REQUEST\n- RESOURCE_NOT_FOUND\n- CONFLICT\n- INTERNAL_SERVER_ERROR",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get registration verification",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification ID",
                        "name": "verification_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.GetVerificationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid verification ID",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Verification not found",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Verification is no longer pending",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register/verification/{verification_id}/pin": {
            "post": {
                "description": "Generate and send a verification PIN for a pending registration.\nPossible error codes:\n- VERIFICATION_NOT_PENDING\n- REGISTRATION_NOT_PENDING\n- REGISTRATION_EXPIRED\n- RESOURCE_NOT_FOUND\n- INTERNAL_SERVER_ERROR",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Create verification PIN",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification ID",
                        "name": "verification_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/registration.CreatePINAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid verification ID",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Verification not found",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Verification or registration conflict",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register/verification/{verification_id}/resend": {
            "post": {
                "description": "Generate and send a new verification PIN for a pending registration.\nPossible error codes:\n- VERIFICATION_NOT_PENDING\n- REGISTRATION_NOT_PENDING\n- REGISTRATION_EXPIRED\n- VERIFICATION_RESEND_COOLDOWN\n- RESOURCE_NOT_FOUND\n- INTERNAL_SERVER_ERROR",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Resend verification PIN",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification ID",
                        "name": "verification_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.ResendVerificationAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid verification ID",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Verification not found",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Verification or registration conflict",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register/verification/{verification_id}/verify": {
            "post": {
                "description": "Verify a registration using the verification PIN.\nPossible error codes:\n- VERIFICATION_NOT_PENDING\n- REGISTRATION_NOT_PENDING\n- REGISTRATION_EXPIRED\n- VERIFICATION_CODE_ATTEMPTS_EXCEEDED\n- INVALID_VERIFICATION_CODE\n- RESOURCE_NOT_FOUND\n- INTERNAL_SERVER_ERROR",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification ID",
                        "name": "verification_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Verification request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/registration.VerifyRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.VerifyRegistrationAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Verification not found",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Verification conflict",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "registration.CreatePINAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/registration.CreatePINResponse"
                },
                "message": {
                    "type": "string",
                    "example": "verification PIN created"
                }
            }
        },
        "registration.CreatePINResponse": {
            "type": "object",
            "properties": {
                "verification_id": {
                    "type": "string",
                    "example": "01a0f359-093b-737a-963a-80f7ca6768ed"
                }
            }
        },
        "registration.FinalizeManualRegistrationAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/registration.FinalizeManualRegistrationResponse"
                },
                "message": {
                    "type": "string",
                    "example": "registration completed successfully"
                }
            }
        },
        "registration.FinalizeManualRegistrationRequest": {
            "type": "object",
            "required": [
                "display_name",
                "password"
            ],
            "properties": {
                "display_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "password123"
                }
            }
        },
        "registration.FinalizeManualRegistrationResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "registration.FinalizeSocialRegistrationAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/registration.FinalizeSocialRegistrationResponse"
                },
                "message": {
                    "type": "string",
                    "example": "registration completed successfully"
                }
            }
        },
        "registration.FinalizeSocialRegistrationRequest": {
            "type": "object",
            "required": [
                "display_name"
            ],
            "properties": {
                "display_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "John Doe"
                }
            }
        },
        "registration.FinalizeSocialRegistrationResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiJ9..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "v1.refresh-token-example"
                },
                "user": {
                    "$ref": "#/definitions/registration.FinalizeSocialRegistrationUser"
                }
            }
        },
        "registration.FinalizeSocialRegistrationUser": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "01a0f359-093b-737a-963a-80f7ca6768ed"
                }
            }
        },
        "registration.GetRegistrationContinuationAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/registration.GetRegistrationContinuationResponse"
                },
                "message": {
                    "type": "string",
                    "example": "registration continuation is valid"
                }
            }
        },
        "registration.GetRegistrationContinuationResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "registration_type": {
                    "type": "string",
                    "example": "manual"
                },
                "requires_password": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "registration.GetVerificationResponse": {
            "type": "object",
            "properties": {
                "pin_issued": {
                    "type": "boolean",
                    "example": true
                },
                "resend_in_seconds": {
                    "type": "integer",
                    "example": 42
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "verification_id": {
                    "type": "string",
                    "example": "01a0f359-093b-737a-963a-80f7ca6768ed"
                }
            }
        },
        "registration.RegisterAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/registration.RegisterResponse"
                },
                "message": {
                    "type": "string",
                    "example": "verification code sent"
                }
            }
        },
        "registration.RegisterRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "user@example.com"
                }
            }
        },
        "registration.RegisterResponse": {
            "type": "object",
            "properties": {
                "verification_id": {
                    "type": "string",
                    "example": "01a0f359-093b-737a-963a-80f7ca6768ed"
                }
            }
        },
        "registration.ResendVerificationAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/registration.ResendVerificationResponse"
                },
                "message": {
                    "type": "string",
                    "example": "verification code resent"
                }
            }
        },
        "registration.ResendVerificationResponse": {
            "type": "object",
            "properties": {
                "verification_id": {
                    "type": "string",
                    "example": "01a0f359-093b-737a-963a-80f7ca6768ed"
                }
            }
        },
        "registration.VerifyRegistrationAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/registration.VerifyRegistrationResponse"
                },
                "message": {
                    "type": "string",
                    "example": "registration verified"
                }
            }
        },
        "registration.VerifyRegistrationRequest": {
            "type": "object",
            "required": [
                "pin"
            ],
            "properties": {
                "pin": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "registration.VerifyRegistrationResponse": {
            "type": "object",
            "properties": {
                "registration_continuation_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiJ9..."
                }
            }
        },
        "swagger.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ERROR_CODE"
                },
                "message": {
                    "type": "string",
                    "example": "request failed"
                }
            }
        },
        "swagger.APIErrorField": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string",
                    "example": "email"
                },
                "message": {
                    "type": "string",
                    "example": "invalid email"
                }
            }
        },
        "swagger.APIErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/swagger.APIError"
                }
            }
        },
        "swagger.ValidationError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.APIErrorField"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "validation failed"
                }
            }
        },
        "swagger.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/swagger.ValidationError"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Stash It API",
	Description:      "REST API for Stash It.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
