// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\api\auth\password_reset\repository.go
//
// Generated by this command:
//
//	mockgen -typed -source .\internal\api\auth\password_reset\repository.go -destination .\internal\api\auth\password_reset\mocks\repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	password_reset "github.com/thoriqr/stash-it-backend/internal/api/auth/password_reset"
	passwordresetdb "github.com/thoriqr/stash-it-backend/internal/api/auth/password_reset/generated"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CompleteVerification mocks base method.
func (m *MockRepository) CompleteVerification(ctx context.Context, params password_reset.CompleteVerificationParams) (passwordresetdb.PasswordResetContinuation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteVerification", ctx, params)
	ret0, _ := ret[0].(passwordresetdb.PasswordResetContinuation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteVerification indicates an expected call of CompleteVerification.
func (mr *MockRepositoryMockRecorder) CompleteVerification(ctx, params any) *MockRepositoryCompleteVerificationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteVerification", reflect.TypeOf((*MockRepository)(nil).CompleteVerification), ctx, params)
	return &MockRepositoryCompleteVerificationCall{Call: call}
}

// MockRepositoryCompleteVerificationCall wrap *gomock.Call
type MockRepositoryCompleteVerificationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCompleteVerificationCall) Return(arg0 passwordresetdb.PasswordResetContinuation, arg1 error) *MockRepositoryCompleteVerificationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCompleteVerificationCall) Do(f func(context.Context, password_reset.CompleteVerificationParams) (passwordresetdb.PasswordResetContinuation, error)) *MockRepositoryCompleteVerificationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCompleteVerificationCall) DoAndReturn(f func(context.Context, password_reset.CompleteVerificationParams) (passwordresetdb.PasswordResetContinuation, error)) *MockRepositoryCompleteVerificationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreatePasswordReset mocks base method.
func (m *MockRepository) CreatePasswordReset(ctx context.Context, params password_reset.CreatePasswordResetParams) (passwordresetdb.VerificationRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePasswordReset", ctx, params)
	ret0, _ := ret[0].(passwordresetdb.VerificationRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePasswordReset indicates an expected call of CreatePasswordReset.
func (mr *MockRepositoryMockRecorder) CreatePasswordReset(ctx, params any) *MockRepositoryCreatePasswordResetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePasswordReset", reflect.TypeOf((*MockRepository)(nil).CreatePasswordReset), ctx, params)
	return &MockRepositoryCreatePasswordResetCall{Call: call}
}

// MockRepositoryCreatePasswordResetCall wrap *gomock.Call
type MockRepositoryCreatePasswordResetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreatePasswordResetCall) Return(arg0 passwordresetdb.VerificationRequest, arg1 error) *MockRepositoryCreatePasswordResetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreatePasswordResetCall) Do(f func(context.Context, password_reset.CreatePasswordResetParams) (passwordresetdb.VerificationRequest, error)) *MockRepositoryCreatePasswordResetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreatePasswordResetCall) DoAndReturn(f func(context.Context, password_reset.CreatePasswordResetParams) (passwordresetdb.VerificationRequest, error)) *MockRepositoryCreatePasswordResetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetActivePasswordResetByEmail mocks base method.
func (m *MockRepository) GetActivePasswordResetByEmail(ctx context.Context, email string) (passwordresetdb.GetActivePasswordResetByEmailRow, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivePasswordResetByEmail", ctx, email)
	ret0, _ := ret[0].(passwordresetdb.GetActivePasswordResetByEmailRow)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetActivePasswordResetByEmail indicates an expected call of GetActivePasswordResetByEmail.
func (mr *MockRepositoryMockRecorder) GetActivePasswordResetByEmail(ctx, email any) *MockRepositoryGetActivePasswordResetByEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivePasswordResetByEmail", reflect.TypeOf((*MockRepository)(nil).GetActivePasswordResetByEmail), ctx, email)
	return &MockRepositoryGetActivePasswordResetByEmailCall{Call: call}
}

// MockRepositoryGetActivePasswordResetByEmailCall wrap *gomock.Call
type MockRepositoryGetActivePasswordResetByEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetActivePasswordResetByEmailCall) Return(arg0 passwordresetdb.GetActivePasswordResetByEmailRow, arg1 bool, arg2 error) *MockRepositoryGetActivePasswordResetByEmailCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetActivePasswordResetByEmailCall) Do(f func(context.Context, string) (passwordresetdb.GetActivePasswordResetByEmailRow, bool, error)) *MockRepositoryGetActivePasswordResetByEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetActivePasswordResetByEmailCall) DoAndReturn(f func(context.Context, string) (passwordresetdb.GetActivePasswordResetByEmailRow, bool, error)) *MockRepositoryGetActivePasswordResetByEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetActiveVerificationCode mocks base method.
func (m *MockRepository) GetActiveVerificationCode(ctx context.Context, verificationRequestID uuid.UUID, maxAttempts int32) (passwordresetdb.VerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveVerificationCode", ctx, verificationRequestID, maxAttempts)
	ret0, _ := ret[0].(passwordresetdb.VerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveVerificationCode indicates an expected call of GetActiveVerificationCode.
func (mr *MockRepositoryMockRecorder) GetActiveVerificationCode(ctx, verificationRequestID, maxAttempts any) *MockRepositoryGetActiveVerificationCodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveVerificationCode", reflect.TypeOf((*MockRepository)(nil).GetActiveVerificationCode), ctx, verificationRequestID, maxAttempts)
	return &MockRepositoryGetActiveVerificationCodeCall{Call: call}
}

// MockRepositoryGetActiveVerificationCodeCall wrap *gomock.Call
type MockRepositoryGetActiveVerificationCodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetActiveVerificationCodeCall) Return(arg0 passwordresetdb.VerificationCode, arg1 error) *MockRepositoryGetActiveVerificationCodeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetActiveVerificationCodeCall) Do(f func(context.Context, uuid.UUID, int32) (passwordresetdb.VerificationCode, error)) *MockRepositoryGetActiveVerificationCodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetActiveVerificationCodeCall) DoAndReturn(f func(context.Context, uuid.UUID, int32) (passwordresetdb.VerificationCode, error)) *MockRepositoryGetActiveVerificationCodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPasswordResetContinuation mocks base method.
func (m *MockRepository) GetPasswordResetContinuation(ctx context.Context, tokenHash string) (passwordresetdb.GetPasswordResetContinuationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordResetContinuation", ctx, tokenHash)
	ret0, _ := ret[0].(passwordresetdb.GetPasswordResetContinuationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordResetContinuation indicates an expected call of GetPasswordResetContinuation.
func (mr *MockRepositoryMockRecorder) GetPasswordResetContinuation(ctx, tokenHash any) *MockRepositoryGetPasswordResetContinuationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordResetContinuation", reflect.TypeOf((*MockRepository)(nil).GetPasswordResetContinuation), ctx, tokenHash)
	return &MockRepositoryGetPasswordResetContinuationCall{Call: call}
}

// MockRepositoryGetPasswordResetContinuationCall wrap *gomock.Call
type MockRepositoryGetPasswordResetContinuationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetPasswordResetContinuationCall) Return(arg0 passwordresetdb.GetPasswordResetContinuationRow, arg1 error) *MockRepositoryGetPasswordResetContinuationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetPasswordResetContinuationCall) Do(f func(context.Context, string) (passwordresetdb.GetPasswordResetContinuationRow, error)) *MockRepositoryGetPasswordResetContinuationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetPasswordResetContinuationCall) DoAndReturn(f func(context.Context, string) (passwordresetdb.GetPasswordResetContinuationRow, error)) *MockRepositoryGetPasswordResetContinuationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(ctx context.Context, email string) (passwordresetdb.GetUserByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(passwordresetdb.GetUserByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(ctx, email any) *MockRepositoryGetUserByEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), ctx, email)
	return &MockRepositoryGetUserByEmailCall{Call: call}
}

// MockRepositoryGetUserByEmailCall wrap *gomock.Call
type MockRepositoryGetUserByEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetUserByEmailCall) Return(arg0 passwordresetdb.GetUserByEmailRow, arg1 error) *MockRepositoryGetUserByEmailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetUserByEmailCall) Do(f func(context.Context, string) (passwordresetdb.GetUserByEmailRow, error)) *MockRepositoryGetUserByEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetUserByEmailCall) DoAndReturn(f func(context.Context, string) (passwordresetdb.GetUserByEmailRow, error)) *MockRepositoryGetUserByEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetVerification mocks base method.
func (m *MockRepository) GetVerification(ctx context.Context, id uuid.UUID) (passwordresetdb.GetVerificationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerification", ctx, id)
	ret0, _ := ret[0].(passwordresetdb.GetVerificationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerification indicates an expected call of GetVerification.
func (mr *MockRepositoryMockRecorder) GetVerification(ctx, id any) *MockRepositoryGetVerificationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerification", reflect.TypeOf((*MockRepository)(nil).GetVerification), ctx, id)
	return &MockRepositoryGetVerificationCall{Call: call}
}

// MockRepositoryGetVerificationCall wrap *gomock.Call
type MockRepositoryGetVerificationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetVerificationCall) Return(arg0 passwordresetdb.GetVerificationRow, arg1 error) *MockRepositoryGetVerificationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetVerificationCall) Do(f func(context.Context, uuid.UUID) (passwordresetdb.GetVerificationRow, error)) *MockRepositoryGetVerificationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetVerificationCall) DoAndReturn(f func(context.Context, uuid.UUID) (passwordresetdb.GetVerificationRow, error)) *MockRepositoryGetVerificationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncrementVerificationCodeAttempts mocks base method.
func (m *MockRepository) IncrementVerificationCodeAttempts(ctx context.Context, id uuid.UUID, maxAttempts int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementVerificationCodeAttempts", ctx, id, maxAttempts)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementVerificationCodeAttempts indicates an expected call of IncrementVerificationCodeAttempts.
func (mr *MockRepositoryMockRecorder) IncrementVerificationCodeAttempts(ctx, id, maxAttempts any) *MockRepositoryIncrementVerificationCodeAttemptsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementVerificationCodeAttempts", reflect.TypeOf((*MockRepository)(nil).IncrementVerificationCodeAttempts), ctx, id, maxAttempts)
	return &MockRepositoryIncrementVerificationCodeAttemptsCall{Call: call}
}

// MockRepositoryIncrementVerificationCodeAttemptsCall wrap *gomock.Call
type MockRepositoryIncrementVerificationCodeAttemptsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryIncrementVerificationCodeAttemptsCall) Return(arg0 int32, arg1 error) *MockRepositoryIncrementVerificationCodeAttemptsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryIncrementVerificationCodeAttemptsCall) Do(f func(context.Context, uuid.UUID, int32) (int32, error)) *MockRepositoryIncrementVerificationCodeAttemptsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryIncrementVerificationCodeAttemptsCall) DoAndReturn(f func(context.Context, uuid.UUID, int32) (int32, error)) *MockRepositoryIncrementVerificationCodeAttemptsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResendVerification mocks base method.
func (m *MockRepository) ResendVerification(ctx context.Context, params password_reset.ResendVerificationParams) (passwordresetdb.VerificationRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendVerification", ctx, params)
	ret0, _ := ret[0].(passwordresetdb.VerificationRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResendVerification indicates an expected call of ResendVerification.
func (mr *MockRepositoryMockRecorder) ResendVerification(ctx, params any) *MockRepositoryResendVerificationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendVerification", reflect.TypeOf((*MockRepository)(nil).ResendVerification), ctx, params)
	return &MockRepositoryResendVerificationCall{Call: call}
}

// MockRepositoryResendVerificationCall wrap *gomock.Call
type MockRepositoryResendVerificationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryResendVerificationCall) Return(arg0 passwordresetdb.VerificationRequest, arg1 error) *MockRepositoryResendVerificationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryResendVerificationCall) Do(f func(context.Context, password_reset.ResendVerificationParams) (passwordresetdb.VerificationRequest, error)) *MockRepositoryResendVerificationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryResendVerificationCall) DoAndReturn(f func(context.Context, password_reset.ResendVerificationParams) (passwordresetdb.VerificationRequest, error)) *MockRepositoryResendVerificationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpsertPasswordCredentialAndCompleteReset mocks base method.
func (m *MockRepository) UpsertPasswordCredentialAndCompleteReset(ctx context.Context, params password_reset.UpsertPasswordCredentialAndCompleteResetParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPasswordCredentialAndCompleteReset", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPasswordCredentialAndCompleteReset indicates an expected call of UpsertPasswordCredentialAndCompleteReset.
func (mr *MockRepositoryMockRecorder) UpsertPasswordCredentialAndCompleteReset(ctx, params any) *MockRepositoryUpsertPasswordCredentialAndCompleteResetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPasswordCredentialAndCompleteReset", reflect.TypeOf((*MockRepository)(nil).UpsertPasswordCredentialAndCompleteReset), ctx, params)
	return &MockRepositoryUpsertPasswordCredentialAndCompleteResetCall{Call: call}
}

// MockRepositoryUpsertPasswordCredentialAndCompleteResetCall wrap *gomock.Call
type MockRepositoryUpsertPasswordCredentialAndCompleteResetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpsertPasswordCredentialAndCompleteResetCall) Return(arg0 error) *MockRepositoryUpsertPasswordCredentialAndCompleteResetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpsertPasswordCredentialAndCompleteResetCall) Do(f func(context.Context, password_reset.UpsertPasswordCredentialAndCompleteResetParams) error) *MockRepositoryUpsertPasswordCredentialAndCompleteResetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpsertPasswordCredentialAndCompleteResetCall) DoAndReturn(f func(context.Context, password_reset.UpsertPasswordCredentialAndCompleteResetParams) error) *MockRepositoryUpsertPasswordCredentialAndCompleteResetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
